import { NextResponse } from "next/server";
import { PublicKey } from "@solana/web3.js";
import { getPublicOrb, orbGameType } from "@/lib/orbStore";
import { hasEligibilityReceipt } from "@/lib/eligibility";
import { hasFairPlayReceipt } from "@/lib/fairPlay";
import { hasFollowProof, hasShareProof, hasWalletProof } from "@/lib/qualification";
import { hasHumanProof } from "@/lib/turnstile";
import { getCurrentXSession } from "@/lib/xAuth";
import { getWinner } from "@/lib/upstashWinner";
import { orbEndsAt } from "@/lib/orbLifecycle";
import { assignRaceEntrantProfile, getRaceEntrantProfile } from "@/lib/raceEntrants";
import { issueRaceJoinToken, raceRealtimeUrl, raceRuntimeConfigured, raceRuntimeHealthy } from "@/lib/raceRuntime";
import { RACE_GAME_VERSION } from "@/game/race";
import { COMPETITION_RESTRICTION_MESSAGE, getCompetitionRestriction } from "@/lib/gameIntegrity";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=20;
function walletOf(value:unknown){if(typeof value!=="string")return null;try{return new PublicKey(value).toBase58()}catch{return null}}
export async function POST(request:Request,{params}:{params:Promise<{slug:string}>}){const{slug}=await params;const[orb,x]=await Promise.all([getPublicOrb(slug),getCurrentXSession()]);if(!orb||orbGameType(orb)!=="race")return NextResponse.json({ok:false,error:"Race not found"},{status:404});if(!x)return NextResponse.json({ok:false,error:"Connect X first"},{status:401});if(orb.generatorVersion!==RACE_GAME_VERSION)return NextResponse.json({ok:false,error:"This Race was funded under a different gameplay version and cannot be silently upgraded."},{status:409});if(!raceRuntimeConfigured())return NextResponse.json({ok:false,error:"Race realtime service is not configured"},{status:503});if(!await raceRuntimeHealthy())return NextResponse.json({ok:false,error:"Race realtime service is not healthy or is running a mismatched game version"},{status:503});if(Date.now()<orb.startsAt-60_000)return NextResponse.json({ok:false,error:"RACE_NOT_OPEN",startsAt:orb.startsAt},{status:403});const endsAt=orbEndsAt(orb);if(Date.now()>=endsAt||await getWinner(orb.id))return NextResponse.json({ok:false,error:"ORB_CLOSED",endsAt},{status:409});const body=await request.json().catch(()=>({}))as{wallet?:unknown};const wallet=walletOf(body.wallet);if(!wallet)return NextResponse.json({ok:false,error:"Invalid wallet"},{status:400});if(await getCompetitionRestriction(wallet,x.user.id))return NextResponse.json({ok:false,error:COMPETITION_RESTRICTION_MESSAGE,code:"COMPETITION_RESTRICTED"},{status:403});if(!await hasEligibilityReceipt(wallet))return NextResponse.json({ok:false,error:"Confirm 18+ eligibility for this wallet before entering an Orb"},{status:403});if(!await hasFairPlayReceipt(wallet,x.user.id))return NextResponse.json({ok:false,error:"Accept the current Fair Play Policy before entering an Orb",code:"FAIR_PLAY_REQUIRED"},{status:403});const[followed,walletVerified,humanVerified,shared]=await Promise.all([hasFollowProof(x.user.id,orb.hostX.id),hasWalletProof(slug,x.user.id,wallet),hasHumanProof(slug,x.user.id,wallet),hasShareProof(slug,x.user.id,wallet)]);if(!followed||!walletVerified||!humanVerified||!shared)return NextResponse.json({ok:false,error:"Race registration is not complete"},{status:403});let profile=await getRaceEntrantProfile(slug,wallet);if(!profile||profile.xUserId!==x.user.id||profile.followersCount!==(Number.isFinite(x.user.followersCount)?Number(x.user.followersCount):null))profile=await assignRaceEntrantProfile(slug,wallet,x.user);const issued=issueRaceJoinToken({orbId:orb.id,slug,profile,startsAt:orb.startsAt,endsAt,commitment:orb.commitment,style:orb.style});return NextResponse.json({ok:true,realtimeUrl:raceRealtimeUrl(),token:issued.token,profile,startsAt:orb.startsAt,endsAt},{headers:{"Cache-Control":"private, no-store"}})}
