import { hashString } from "./prng";
import type { DriveProfile, GameManifest, ReplayEnvelope, ReplayEvent, ReplayFrame } from "./types";

export const REPLAY_SCHEMA_VERSION = 1 as const;
export const REPLAY_SAMPLE_HZ = 20 as const;

/**
 * Deterministic replay envelope generated by the live game. `replayId` is a compact local
 * fingerprint for diagnostics. The server independently hashes/verifies the canonical replay;
 * never use replayId itself as authorization to move prize funds.
 */
export function buildReplayEnvelope(
  manifest: GameManifest,
  frames: ReplayFrame[],
  events: ReplayEvent[],
  driveProfile: DriveProfile,
  finishTick: number,
  elapsedMs: number,
  resets: number,
  checkpoints: number,
): ReplayEnvelope {
  const canonicalFrames = frames.map((frame) => `${frame.tick}:${frame.x}:${frame.y}`).join("|");
  const canonicalEvents = events.map((event) => `${event.tick}:${event.type}`).join("|");
  const replayId = hashString([
    REPLAY_SCHEMA_VERSION,
    manifest.manifestId,
    manifest.physicsVersion,
    manifest.rapierVersion,
    driveProfile,
    finishTick,
    Math.round(elapsedMs),
    resets,
    checkpoints,
    canonicalFrames,
    canonicalEvents,
  ].join("::")).toString(16).padStart(8, "0").toUpperCase();

  return {
    schemaVersion: REPLAY_SCHEMA_VERSION,
    replayId,
    manifestId: manifest.manifestId,
    generatorVersion: manifest.generatorVersion,
    physicsVersion: manifest.physicsVersion,
    rapierVersion: manifest.rapierVersion,
    sampleHz: REPLAY_SAMPLE_HZ,
    driveProfile,
    finishTick: Math.max(0, Math.trunc(finishTick)),
    elapsedMs: Math.max(0, Math.round(elapsedMs)),
    resets,
    checkpoints,
    frames: frames.map((frame) => ({ ...frame })),
    events: events.map((event) => ({ ...event })),
  };
}
