import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { RACE_GAME_VERSION } from "@/game/race";
import type { GameStyle } from "@/game/types";
import type { RaceEntrantProfile } from "@/lib/raceEntrants";

export const RACE_JOIN_SCHEMA=1 as const;
export type RaceJoinPayload={schemaVersion:typeof RACE_JOIN_SCHEMA;orbId:string;slug:string;wallet:string;xUserId:string;username:string;profileImageUrl?:string|null;followersCount?:number|null;orbColor:string;orbGlow:string;gridQualifiedAt:number;startsAt:number;endsAt:number;commitment:string;style:GameStyle;issuedAt:number;expiresAt:number};
function hmacKey(){const key=(process.env.RACE_RUNTIME_HMAC_KEY||"").trim();if(key.length<32)throw new Error("RACE_RUNTIME_HMAC_KEY must be at least 32 characters");return key}
export function raceRealtimeUrl(){const value=(process.env.NEXT_PUBLIC_RACE_REALTIME_URL||"").trim().replace(/\/$/,"");if(!value)throw new Error("NEXT_PUBLIC_RACE_REALTIME_URL is not configured");const url=new URL(value);if(!/^wss?:$/.test(url.protocol))throw new Error("NEXT_PUBLIC_RACE_REALTIME_URL must be ws:// or wss://");return url.toString().replace(/\/$/,"")}
export function raceRuntimeConfigured(){try{return Boolean(raceRealtimeUrl())&&(process.env.RACE_RUNTIME_HMAC_KEY||"").trim().length>=32}catch{return false}}
function raceHttpUrl(pathname:string){const ws=new URL(raceRealtimeUrl());ws.protocol=ws.protocol==="wss:"?"https:":"http:";ws.pathname=pathname;ws.search="";ws.hash="";return ws.toString()}
export async function raceRuntimeHealthy(timeoutMs=2500){if(!raceRuntimeConfigured())return false;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(raceHttpUrl("/health"),{cache:"no-store",signal:controller.signal,headers:{accept:"application/json"}});if(!response.ok)return false;const payload=await response.json().catch(()=>null) as {ok?:unknown;version?:unknown}|null;return payload?.ok===true&&payload.version===RACE_GAME_VERSION}catch{return false}finally{clearTimeout(timer)}}
function sign(encoded:string){return createHmac("sha256",hmacKey()).update(encoded,"utf8").digest("base64url")}
export function issueRaceJoinToken(input:{orbId:string;slug:string;profile:RaceEntrantProfile;startsAt:number;endsAt:number;commitment:string;style:GameStyle}){const now=Date.now();const payload:RaceJoinPayload={schemaVersion:RACE_JOIN_SCHEMA,orbId:input.orbId,slug:input.slug,wallet:input.profile.wallet,xUserId:input.profile.xUserId,username:input.profile.username,profileImageUrl:input.profile.profileImageUrl||null,followersCount:Number.isFinite(input.profile.followersCount)?Number(input.profile.followersCount):null,orbColor:input.profile.orbColor,orbGlow:input.profile.orbGlow,gridQualifiedAt:input.profile.gridQualifiedAt,startsAt:input.startsAt,endsAt:input.endsAt,commitment:input.commitment,style:input.style,issuedAt:now,expiresAt:Math.min(input.endsAt,now+1000*60*60*6)};const encoded=Buffer.from(JSON.stringify(payload),"utf8").toString("base64url");return{token:`${encoded}.${sign(encoded)}`,payload}}
export function verifyRaceRuntimeRequest(rawBody:string,timestamp:string|null,supplied:string|null){if(!timestamp||!supplied)return false;const stamp=Number(timestamp);if(!Number.isFinite(stamp)||Math.abs(Date.now()-stamp)>120_000)return false;const expected=createHmac("sha256",hmacKey()).update(`${timestamp}.${rawBody}`,"utf8").digest("base64url"),a=Buffer.from(expected,"utf8"),b=Buffer.from(supplied,"utf8");return a.length===b.length&&timingSafeEqual(a,b)}

export async function sendRaceIntegrityControl(input:{action:"ban"|"unban";wallet?:string|null;xUserId?:string|null}){if(!raceRuntimeConfigured())return{ok:false,kicked:0};const body=JSON.stringify({schemaVersion:1,...input}),timestamp=String(Date.now()),signature=createHmac("sha256",hmacKey()).update(`${timestamp}.${body}`,"utf8").digest("base64url");try{const response=await fetch(raceHttpUrl("/admin/control"),{method:"POST",headers:{"content-type":"application/json","x-race-timestamp":timestamp,"x-race-signature":signature},body,signal:AbortSignal.timeout(3500)});const payload=await response.json().catch(()=>null) as {ok?:boolean;kicked?:number}|null;return{ok:response.ok&&payload?.ok===true,kicked:Number(payload?.kicked)||0}}catch{return{ok:false,kicked:0}}}
