[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
orbs_protocol = "464cqCX4vMoQFjeuVinz3R6ccrFz68WqEkSvFSGg7Fns"

[programs.mainnet]
orbs_protocol = "464cqCX4vMoQFjeuVinz3R6ccrFz68WqEkSvFSGg7Fns"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd anchor-tests && npm test"
