"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArenaAudioEngine } from "@/game/arenaAudio";
import { buildArenaConfig, type ArenaPace } from "@/game/arena";
import { clampPlanarSpeed, nextPlanarVelocity } from "@/game/simulation";
import { PHYSICS } from "@/game/constants";
import type { GameStyle } from "@/game/types";

type Props = { playerCount:number; style:GameStyle; seed:string; pace:ArenaPace; generation:number };
type Phase = "ready"|"countdown"|"playing"|"eliminated"|"won"|"finished";
type ControlMode = "keys"|"touch"|"sensor";
type Personality = "hunter"|"survivor"|"racer"|"opportunist";

type OrbSim = {
  id:string; username:string; color:string; body:import("@dimforge/rapier3d-compat").RigidBody;
  mesh:import("three").Mesh; core:import("three").Mesh; label:import("three").Sprite;
  alive:boolean; isHuman:boolean; integrity:number; jumpReadyAt:number; airborne:boolean;
  personality:Personality; botHeading:number; botThinkAt:number; lastLandingVy:number;
};

type MovingSurface = {
  name:string; body:import("@dimforge/rapier3d-compat").RigidBody; mesh:import("three").Mesh;
  base:{x:number;y:number;z:number}; closeAt:number; drop:number; duration:number;
};

type Shockwave = { mesh:import("three").Mesh; born:number; life:number };

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const usernames=["orbitaljup","bonkpilot","madlad","solsurfer","pixelwhale","caturday","degenqueen","mooncrate","zerogravity","mintghost","blockrunner","jupcat","helioroll","voidwalker","tokenpunk","lamportlord","orbmaxi","driftmode","neonape","cryptokite","glasscanon","solanaut","rollhard","bagholder","mevless","chainchaser","memeengine","jupiterian","vaultfox","orbitron","turbocat","liquidjup","candycloud","solstice","nightmarket","airdropkid","ghostroute","mempoolmax","mintcondition","orbitalburn"];

function seeded(seed:string){let h=2166136261;for(let i=0;i<seed.length;i++)h=Math.imul(h^seed.charCodeAt(i),16777619);return()=>{h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return(h>>>0)/4294967296}}
function orbColor(i:number,r:()=>number){const hue=(i*137.508+r()*28)%360;return `hsl(${hue.toFixed(0)} 90% 61%)`}
function seededNumber(seed:string){let n=0;for(let i=0;i<seed.length;i++)n=(n*31+seed.charCodeAt(i))|0;return Math.abs(n)||1}

function makeMountainRing(THREE:typeof import("three"),radius:number,seed:number,y:number,color:string){
  const segments=64,positions:number[]=[];const rand=(n:number)=>{const x=Math.sin((seed+n*19.17)*12.9898)*43758.5453;return x-Math.floor(x)};
  for(let i=0;i<segments;i++){const a0=i/segments*Math.PI*2,a1=(i+1)/segments*Math.PI*2;const h0=1.2+rand(i)*5.4+Math.pow(rand(i+177),4)*7,h1=1.2+rand(i+1)*5.4+Math.pow(rand(i+178),4)*7;const inner=radius*.94;positions.push(Math.cos(a0)*inner,y,Math.sin(a0)*inner,Math.cos(a0)*radius,y+h0,Math.sin(a0)*radius,Math.cos(a1)*radius,y+h1,Math.sin(a1)*radius,Math.cos(a0)*inner,y,Math.sin(a0)*inner,Math.cos(a1)*radius,y+h1,Math.sin(a1)*radius,Math.cos(a1)*inner,y,Math.sin(a1)*inner)}
  const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.92,metalness:.08,side:THREE.DoubleSide}));
}
function makeSky(THREE:typeof import("three"),accent:string){const g=new THREE.SphereGeometry(220,40,24);const m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{uAccent:{value:new THREE.Color(accent)}},vertexShader:`varying vec3 vDir;void main(){vDir=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec3 vDir;uniform vec3 uAccent;void main(){float horizon=pow(1.0-abs(vDir.y),6.0);float zenith=smoothstep(-.15,.9,vDir.y);float aurora=smoothstep(.72,1.0,sin(vDir.x*8.0+vDir.z*10.0+vDir.y*4.0)*.5+.5)*horizon;vec3 deep=vec3(.008,.018,.08),mid=vec3(.035,.07,.22);vec3 color=mix(mid,deep,zenith);color+=uAccent*horizon*.42;color+=vec3(.04,.75,.95)*aurora*.22;gl_FragColor=vec4(color,1.0);}`});return new THREE.Mesh(g,m)}
function makeLabel(THREE:typeof import("three"),text:string,tint:string){const c=document.createElement("canvas");c.width=512;c.height=128;const x=c.getContext("2d")!;x.font="800 46px Arial";const w=Math.min(465,x.measureText(text).width+64),left=(512-w)/2;x.fillStyle="rgba(3,7,18,.7)";x.strokeStyle="rgba(255,255,255,.18)";x.lineWidth=3;x.beginPath();x.roundRect(left,22,w,72,28);x.fill();x.stroke();x.fillStyle=tint;x.beginPath();x.arc(left+29,58,8,0,Math.PI*2);x.fill();x.fillStyle="white";x.textAlign="center";x.fillText(text,256,73);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(2.8,.7,1);return s}
function makeOrbMaterial(THREE:typeof import("three"),primary:string,secondary:string){return new THREE.MeshPhysicalMaterial({color:primary,emissive:new THREE.Color(secondary).multiplyScalar(.34),emissiveIntensity:1.05,roughness:.1,metalness:.08,transmission:.3,thickness:1.2,clearcoat:1,clearcoatRoughness:.06,iridescence:.45,iridescenceIOR:1.62})}

export default function ArenaSandbox({playerCount,style,seed,pace,generation}:Props){
  const mountRef=useRef<HTMLDivElement>(null);
  const controlsRef=useRef({up:false,down:false,left:false,right:false,touchX:0,touchY:0});
  const sensorRef=useRef({active:false,beta:0,gamma:0,neutralBeta:0,neutralGamma:0});
  const jumpRef=useRef<()=>void>(()=>undefined),startRef=useRef<()=>void>(()=>undefined);
  const [phase,setPhase]=useState<Phase>("ready"),[countdown,setCountdown]=useState(0),[survivors,setSurvivors]=useState(playerCount),[elapsed,setElapsed]=useState(0),[integrity,setIntegrity]=useState(100),[jumpCooldown,setJumpCooldown]=useState(0),[winner,setWinner]=useState<string|null>(null),[eventText,setEventText]=useState("LAST ORB STANDING"),[controlMode,setControlMode]=useState<ControlMode>("keys"),[sensorAvailable,setSensorAvailable]=useState(false);
  const controlModeRef=useRef<ControlMode>("keys");
  const config=useMemo(()=>buildArenaConfig({playerCount,pace,style,seed}),[playerCount,pace,style,seed]);

  const requestMotion=useCallback(async()=>{const E=window.DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<"granted"|"denied">};try{if(typeof E.requestPermission==="function"&&(await E.requestPermission())!=="granted")return;sensorRef.current.neutralBeta=sensorRef.current.beta;sensorRef.current.neutralGamma=sensorRef.current.gamma;sensorRef.current.active=true;controlModeRef.current="sensor";setControlMode("sensor")}catch{}},[]);

  useEffect(()=>{
    const mount=mountRef.current;if(!mount)return;let cancelled=false,frame=0;let cleanupThree:(()=>void)|null=null;const audio=new ArenaAudioEngine();
    setPhase("ready");setSurvivors(playerCount);setElapsed(0);setIntegrity(100);setWinner(null);setEventText("LAST ORB STANDING");setJumpCooldown(0);
    const orientation=(e:DeviceOrientationEvent)=>{sensorRef.current.beta=e.beta??0;sensorRef.current.gamma=e.gamma??0};window.addEventListener("deviceorientation",orientation);if("DeviceOrientationEvent" in window)setSensorAvailable(true);if(window.matchMedia("(pointer: coarse)").matches){controlModeRef.current="touch";setControlMode("touch")}
    const onKey=(e:KeyboardEvent,down:boolean)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","KeyW","KeyA","KeyS","KeyD","Space"].includes(e.code))e.preventDefault();if(e.code==="ArrowUp"||e.code==="KeyW")controlsRef.current.up=down;if(e.code==="ArrowDown"||e.code==="KeyS")controlsRef.current.down=down;if(e.code==="ArrowLeft"||e.code==="KeyA")controlsRef.current.left=down;if(e.code==="ArrowRight"||e.code==="KeyD")controlsRef.current.right=down;if(e.code==="Space"&&down&&!e.repeat)jumpRef.current()};const kd=(e:KeyboardEvent)=>onKey(e,true),ku=(e:KeyboardEvent)=>onKey(e,false);window.addEventListener("keydown",kd,{passive:false});window.addEventListener("keyup",ku,{passive:false});

    (async()=>{
      const THREE=await import("three"),RAPIER=await import("@dimforge/rapier3d-compat");await RAPIER.init();if(cancelled)return;
      const rand=seeded(`${seed}:${generation}`),seedN=seededNumber(seed),s=config.courseScale;
      const scene=new THREE.Scene();scene.background=new THREE.Color("#050817");scene.fog=new THREE.FogExp2("#080D25",.011);
      const mobileish=window.matchMedia("(pointer: coarse)").matches||window.innerWidth<800;const camera=new THREE.PerspectiveCamera(mobileish?58:52,1,.08,500);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobileish?1.25:1.6));renderer.shadowMap.enabled=true;mount.innerHTML="";mount.appendChild(renderer.domElement);
      scene.add(new THREE.HemisphereLight("#8CF6FF","#07091B",2.05));const sun=new THREE.DirectionalLight("#D9E9FF",3.3);sun.position.set(-16,24,12);sun.castShadow=true;scene.add(sun);const rim=new THREE.DirectionalLight(style.accent,2.6);rim.position.set(15,8,-14);scene.add(rim);scene.add(makeSky(THREE,style.accent));scene.add(makeMountainRing(THREE,48*s,seedN,-3.2,"#10183C"),makeMountainRing(THREE,58*s,seedN+991,-3.5,"#09112B"));
      const starGeo=new THREE.BufferGeometry(),stars:number[]=[];for(let i=0;i<720;i++){const a=rand()*Math.PI*2,r=80+rand()*100,y=8+rand()*88;stars.push(Math.cos(a)*r,y,Math.sin(a)*r)}starGeo.setAttribute("position",new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:"#CBE8FF",size:.09,transparent:true,opacity:.8})));
      const world=new RAPIER.World({x:0,y:-PHYSICS.gravity,z:0});
      const terrainMat=new THREE.MeshPhysicalMaterial({color:style.floor,emissive:new THREE.Color(style.marbleSecondary).multiplyScalar(.13),emissiveIntensity:.7,roughness:.26,metalness:.28,transmission:.16,clearcoat:1,clearcoatRoughness:.12});
      const edgeMat=new THREE.MeshBasicMaterial({color:style.accent,transparent:true,opacity:.45});
      const moving:MovingSurface[]=[];
      const staticMeshes:import("three").Object3D[]=[];
      const quat=(rx:number,ry:number,rz:number)=>{const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(rx,ry,rz));return{x:q.x,y:q.y,z:q.z,w:q.w}};
      function addSurface(name:string,pos:{x:number;y:number;z:number},size:{x:number;y:number;z:number},rot={x:0,y:0,z:0},opts?:{closeAt?:number;drop?:number;duration?:number;color?:string}){
        const movingSurface=typeof opts?.closeAt==="number";const desc=movingSurface?RAPIER.RigidBodyDesc.kinematicPositionBased():RAPIER.RigidBodyDesc.fixed();desc.setTranslation(pos.x,pos.y,pos.z).setRotation(quat(rot.x,rot.y,rot.z));const body=world.createRigidBody(desc);world.createCollider(RAPIER.ColliderDesc.cuboid(size.x/2,size.y/2,size.z/2).setFriction(.56).setRestitution(.05),body);
        const mat=opts?.color?new THREE.MeshPhysicalMaterial({color:opts.color,emissive:new THREE.Color(style.accent).multiplyScalar(.1),roughness:.25,metalness:.3,clearcoat:1}):terrainMat;const mesh=new THREE.Mesh(new THREE.BoxGeometry(size.x,size.y,size.z,1,1,1),mat);mesh.position.set(pos.x,pos.y,pos.z);mesh.rotation.set(rot.x,rot.y,rot.z);mesh.receiveShadow=true;mesh.castShadow=true;scene.add(mesh);staticMeshes.push(mesh);
        const outline=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry as import("three").BufferGeometry),new THREE.LineBasicMaterial({color:style.accent,transparent:true,opacity:.18}));outline.position.copy(mesh.position);outline.rotation.copy(mesh.rotation);scene.add(outline);staticMeshes.push(outline);
        if(movingSurface)moving.push({name,body,mesh,base:pos,closeAt:opts!.closeAt!,drop:opts?.drop??8,duration:opts?.duration??4});return body;
      }
      function addRamp(name:string,x:number,z:number,axis:"x"|"z",dir:number,closeAt?:number){const length=6.8*s,width=5.1*s,angle=.19*dir;const rot=axis==="z"?{x:-angle,y:0,z:0}:{x:0,y:0,z:angle};const size=axis==="z"?{x:width,y:.42,z:length}:{x:length,y:.42,z:width};return addSurface(name,{x,y:.75,z},size,rot,typeof closeAt==="number"?{closeAt}:undefined)}
      // Four broad districts, elevated summit, ramps, and cross-routes. No perimeter walls.
      const d=12.5*s, court=9.2*s, thick=.48;
      addSurface("summit",{x:0,y:1.25,z:0},{x:10.2*s,y:.6,z:10.2*s});
      addSurface("north court",{x:0,y:0,z:-d},{x:court,y:thick,z:8.2*s},{x:0,y:0,z:0},{closeAt:config.innerCloseAt+10,drop:9});
      addSurface("south court",{x:0,y:0,z:d},{x:court,y:thick,z:8.2*s},{x:0,y:0,z:0},{closeAt:config.innerCloseAt+4,drop:9});
      addSurface("west court",{x:-d,y:0,z:0},{x:8.2*s,y:thick,z:court},{x:0,y:0,z:0},{closeAt:config.outerCloseAt,drop:9});
      addSurface("east court",{x:d,y:0,z:0},{x:8.2*s,y:thick,z:court},{x:0,y:0,z:0},{closeAt:config.outerCloseAt+8,drop:9});
      addRamp("north ramp",0,-6.3*s,"z",1,config.finalCollapseAt);addRamp("south ramp",0,6.3*s,"z",-1,config.finalCollapseAt);addRamp("west ramp",-6.3*s,0,"x",1,config.finalCollapseAt);addRamp("east ramp",6.3*s,0,"x",-1,config.finalCollapseAt);
      // Diagonal escape bridges create route choice and prevent center clustering.
      const bridgeL=8.4*s;[[ -8.4,-8.4,Math.PI/4],[8.4,-8.4,-Math.PI/4],[-8.4,8.4,-Math.PI/4],[8.4,8.4,Math.PI/4]].forEach(([x,z,r],i)=>addSurface(`outer bridge ${i+1}`,{x:x*s/1,z:z*s/1,y:.18},{x:bridgeL,y:.36,z:2.7*s},{x:0,y:r,z:0},{closeAt:config.outerCloseAt+12+i*3,drop:8}));
      // Skill terrain: buried spheres form smooth hills; fixed posts are intentional bounce objects.
      const hillMat=new THREE.MeshPhysicalMaterial({color:style.floor,emissive:new THREE.Color(style.marbleSecondary).multiplyScalar(.2),emissiveIntensity:.8,roughness:.2,metalness:.22,clearcoat:1});
      [[-2.8,-d],[2.9,-d],[-d,2.8],[d,-2.8]].forEach(([x,z],i)=>{const rad=2.2*s;const body=world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,-rad+.25,z));world.createCollider(RAPIER.ColliderDesc.ball(rad).setFriction(.65).setRestitution(.02),body);const mesh=new THREE.Mesh(new THREE.SphereGeometry(rad,32,18),hillMat);mesh.position.set(x,-rad+.25,z);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);staticMeshes.push(mesh)});
      const bumperMat=new THREE.MeshPhysicalMaterial({color:style.marbleSecondary,emissive:style.accent,emissiveIntensity:1.4,roughness:.16,metalness:.36,clearcoat:1});
      [[-3.7*s,-d],[3.7*s,-d],[-d,-3.7*s],[d,3.7*s],[-3.2*s,3.2*s],[3.2*s,-3.2*s]].forEach(([x,z])=>{const body=world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,.62,z));world.createCollider(RAPIER.ColliderDesc.cylinder(.62,.62).setRestitution(.8).setFriction(.2),body);const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.62,.68,1.24,28),bumperMat);mesh.position.set(x,.62,z);mesh.castShadow=true;scene.add(mesh);staticMeshes.push(mesh)});
      // A readable opening floor gate at the north approach: three panels breathe on a fixed rhythm.
      const gatePanels:MovingSurface[]=[];[-1,0,1].forEach((n)=>{const body=RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(n*2.15*s,.32,-8.9*s);const rb=world.createRigidBody(body);world.createCollider(RAPIER.ColliderDesc.cuboid(.95*s,.16,1.25*s).setFriction(.55),rb);const mesh=new THREE.Mesh(new THREE.BoxGeometry(1.9*s,.32,2.5*s),new THREE.MeshPhysicalMaterial({color:style.walls,emissive:style.accent,emissiveIntensity:.9,roughness:.18,metalness:.35,clearcoat:1}));mesh.position.set(n*2.15*s,.32,-8.9*s);scene.add(mesh);gatePanels.push({name:`pulse panel ${n}`,body:rb,mesh,base:{x:n*2.15*s,y:.32,z:-8.9*s},closeAt:0,drop:2.8,duration:1})});

      const orbGeo=new THREE.SphereGeometry(PHYSICS.ballRadius,40,28),coreGeo=new THREE.SphereGeometry(PHYSICS.ballRadius*.69,28,18);const orbs:OrbSim[]=[];
      const spawnCenters=[[0,d],[-d,0],[d,0],[0,-d]];for(let i=0;i<playerCount;i++){const human=i===0,center=spawnCenters[i%spawnCenters.length]!,slot=Math.floor(i/4),a=(slot*2.399+i*.31)%(Math.PI*2),ring=1.15+Math.sqrt(slot)*.62;let x=center[0]+Math.cos(a)*ring,z=center[1]+Math.sin(a)*ring;if(human){x=0;z=d+1.1*s}const color=human?style.marble:orbColor(i,rand),secondary=human?style.marbleSecondary:color;const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,1.15,z).setLinearDamping(PHYSICS.linearDamping).setAngularDamping(PHYSICS.angularDamping).setCcdEnabled(true));world.createCollider(RAPIER.ColliderDesc.ball(PHYSICS.ballRadius).setDensity(1).setFriction(PHYSICS.friction).setRestitution(.16),body);const mat=makeOrbMaterial(THREE,color,secondary),mesh=new THREE.Mesh(orbGeo,mat);mesh.castShadow=true;const core=new THREE.Mesh(coreGeo,new THREE.MeshBasicMaterial({color:secondary,transparent:true,opacity:.17}));mesh.add(core);const label=makeLabel(THREE,human?"@you":`@${usernames[(i-1)%usernames.length]}`,color);label.position.set(0,1.2,0);mesh.add(label);scene.add(mesh);orbs.push({id:`orb-${i}`,username:human?"@you":`@${usernames[(i-1)%usernames.length]}`,color,body,mesh,core,label,alive:true,isHuman:human,integrity:100,jumpReadyAt:0,airborne:false,personality:(['hunter','survivor','racer','opportunist'] as Personality[])[i%4]!,botHeading:rand()*Math.PI*2,botThinkAt:0,lastLandingVy:0})}
      const human=orbs[0]!;const shocks:Shockwave[]=[];const pairHits=new Map<string,number>();let cameraShake=0,lastFacing=new THREE.Vector3(0,0,-1),matchStart=0,live=false,resolved=false,lastUi=0,acc=0,prev=performance.now(),simTime=0;
      const burst=(x:number,y:number,z:number,power:number,color:string)=>{const g=new THREE.SphereGeometry(.5,20,12),m=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.45,wireframe:true}),mesh=new THREE.Mesh(g,m);mesh.position.set(x,y,z);scene.add(mesh);shocks.push({mesh,born:performance.now(),life:260+power*180});cameraShake=Math.max(cameraShake,.05+power*.13)};
      const eliminate=(o:OrbSim,reason="fell from the course")=>{if(!o.alive)return;o.alive=false;o.body.setEnabled(false);o.mesh.visible=false;const alive=orbs.filter(v=>v.alive);setSurvivors(alive.length);if(o.isHuman){setPhase("eliminated");setEventText("YOU'RE OUT · SPECTATING");audio.eliminated()}else setEventText(`${o.username} ${reason}`);if(alive.length<=1&&!resolved){resolved=true;const w=alive[0];setWinner(w?.username??null);if(w?.isHuman){setPhase("won");audio.victory()}else setPhase("finished");setEventText(w ? `${w.username} WINS` : "MATCH COMPLETE")}}
      const grounded=(o:OrbSim)=>{const p=o.body.translation(),v=o.body.linvel();return Math.abs(v.y)<.62&&p.y<3.4};
      const jump=(o:OrbSim)=>{if(!live||!o.alive)return;const now=performance.now();if(now<o.jumpReadyAt||!grounded(o))return;const v=o.body.linvel();o.body.setLinvel({x:v.x,y:config.jumpImpulse,z:v.z},true);o.jumpReadyAt=now+config.jumpCooldownMs;o.airborne=true;if(o.isHuman)audio.jump()};jumpRef.current=()=>jump(human);
      const start=()=>{if(live)return;setPhase("countdown");audio.startMusic();let n=3;setCountdown(n);const timer=window.setInterval(()=>{n-=1;setCountdown(n);if(n<=0){window.clearInterval(timer);setCountdown(0);setPhase("playing");setEventText("COURSE OPEN · BUILD SPEED");matchStart=performance.now();live=true}},650)};startRef.current=start;

      function handleImpacts(now:number){const cellSize=1.15,buckets=new Map<string,OrbSim[]>();for(const o of orbs){if(!o.alive)continue;const p=o.body.translation(),k=`${Math.floor(p.x/cellSize)},${Math.floor(p.z/cellSize)}`;const b=buckets.get(k);if(b)b.push(o);else buckets.set(k,[o])}const seen=new Set<string>();for(const [key,bucket] of buckets){const [cx,cz]=key.split(',').map(Number);for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){const other=buckets.get(`${cx!+dx},${cz!+dz}`);if(!other)continue;for(const a of bucket)for(const b of other){if(a===b)continue;const pk=a.id<b.id?`${a.id}:${b.id}`:`${b.id}:${a.id}`;if(seen.has(pk))continue;seen.add(pk);const pa=a.body.translation(),pb=b.body.translation(),nx=pb.x-pa.x,nz=pb.z-pa.z,dist=Math.hypot(nx,nz);if(dist>PHYSICS.ballRadius*2.35||dist<.001)continue;const va=a.body.linvel(),vb=b.body.linvel(),ux=nx/dist,uz=nz/dist,closing=Math.max(0,-((vb.x-va.x)*ux+(vb.z-va.z)*uz));const last=pairHits.get(pk)??0;if(closing<1.45||now-last<190)continue;pairHits.set(pk,now);const sa=Math.hypot(va.x,va.z),sb=Math.hypot(vb.x,vb.z),power=clamp((closing-1.2)/3.8,0,1);let attacker=a,target=b;if(sb>sa){attacker=b;target=a}const damage=clamp((closing-1.25)*config.impactDamageScale,2,24);target.integrity=Math.max(0,target.integrity-damage);attacker.integrity=Math.max(0,attacker.integrity-damage*.18);const vulnerability=1+(100-target.integrity)/105;target.body.applyImpulse({x:(target===b?ux:-ux)*(.6+power*1.55)*vulnerability,y:.08+power*.33,z:(target===b?uz:-uz)*(.6+power*1.55)*vulnerability},true);const mx=(pa.x+pb.x)/2,my=(pa.y+pb.y)/2,mz=(pa.z+pb.z)/2;burst(mx,my,mz,power,target.color);audio.bump(.35+power*.9);if(power>.48)setEventText(`${attacker.username} CRUSHED ${target.username} · ${Math.round(damage)} IMPACT`);if(a.isHuman||b.isHuman)setIntegrity(Math.round(human.integrity));if(target.integrity<=0){burst(pb.x,pb.y,pb.z,1,target.color);eliminate(target,"SHATTERED")}}}}}
      function updateMoving(matchElapsed:number){for(const surface of moving){const p=clamp((matchElapsed-surface.closeAt)/surface.duration,0,1),e=p*p*(3-2*p),y=surface.base.y-e*surface.drop;surface.body.setNextKinematicTranslation({x:surface.base.x,y,z:surface.base.z});surface.mesh.position.y=y;const mat=surface.mesh.material as import("three").MeshPhysicalMaterial;if(matchElapsed>surface.closeAt-4&&matchElapsed<surface.closeAt)mat.emissiveIntensity=1.2+Math.sin(matchElapsed*8)*.8}const gateStart=config.outerCloseAt*.55;for(let i=0;i<gatePanels.length;i++){const g=gatePanels[i]!,t=Math.max(0,matchElapsed-gateStart),wave=(Math.sin(t*.92+i*.85)+1)/2,drop=t>0?Math.pow(wave,4)*2.6:0;g.body.setNextKinematicTranslation({x:g.base.x,y:g.base.y-drop,z:g.base.z});g.mesh.position.y=g.base.y-drop}}
      function botInput(o:OrbSim,nowSec:number){const p=o.body.translation();if(nowSec>=o.botThinkAt){const enemies=orbs.filter(v=>v.alive&&v!==o);let target=enemies[0];let best=Infinity;for(const e of enemies){const ep=e.body.translation(),dd=Math.hypot(ep.x-p.x,ep.z-p.z);if(dd<best){best=dd;target=e}}const edge=Math.hypot(p.x,p.z)>config.radius*.86;if(edge||o.personality==="survivor"){o.botHeading=Math.atan2(-p.z,-p.x)+(rand()-.5)*.6}else if(target&&(o.personality==="hunter"||o.personality==="opportunist"&&rand()>.35)){const tp=target.body.translation();o.botHeading=Math.atan2(tp.z-p.z,tp.x-p.x)+(rand()-.5)*.28}else{o.botHeading+= (rand()-.5)*1.35}o.botThinkAt=nowSec+.22+rand()*.4;if(target&&best<2.5&&rand()<.22)jump(o)}return{x:Math.cos(o.botHeading),y:-Math.sin(o.botHeading)}}
      const resize=()=>{const r=mount.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(mount);resize();
      const camPos=new THREE.Vector3(),look=new THREE.Vector3(),desired=new THREE.Vector3();
      const render=(ms:number)=>{if(cancelled)return;frame=requestAnimationFrame(render);const dt=Math.min(.05,(ms-prev)/1000);prev=ms;const matchElapsed=live?(ms-matchStart)/1000:0;if(live&&!resolved){setElapsed(matchElapsed);updateMoving(matchElapsed);const alive=orbs.filter(o=>o.alive).length;audio.setIntensity(clamp(Math.max(matchElapsed/config.maxSeconds,1-alive/playerCount),0,1));if(matchElapsed>config.finalCollapseAt)setEventText("FINAL SUMMIT · FLOOR COLLAPSING");else if(matchElapsed>config.suddenDeathAt)setEventText("SUDDEN DEATH · REACH THE SUMMIT");else if(matchElapsed>config.innerCloseAt)setEventText("INNER COURSE CLOSING");else if(matchElapsed>config.outerCloseAt)setEventText("OUTER COURSE DROPPING");acc+=dt;while(acc>=PHYSICS.fixedStep){simTime+=PHYSICS.fixedStep;for(const o of orbs){if(!o.alive)continue;let ix=0,iy=0;if(o.isHuman){const k=controlsRef.current;ix=(k.right?1:0)-(k.left?1:0);iy=(k.up?1:0)-(k.down?1:0);if(controlModeRef.current==="touch"){ix=k.touchX;iy=k.touchY}else if(controlModeRef.current==="sensor"&&sensorRef.current.active){ix=clamp((sensorRef.current.gamma-sensorRef.current.neutralGamma)/PHYSICS.sensorFullScaleDeg,-1,1);iy=clamp(-(sensorRef.current.beta-sensorRef.current.neutralBeta)/PHYSICS.sensorFullScaleDeg,-1,1)}}else{const b=botInput(o,simTime);ix=b.x;iy=b.y}const v=o.body.linvel(),steer=nextPlanarVelocity({x:v.x,z:v.z},ix,iy,o.isHuman&&controlModeRef.current==="keys"?"desktop":"mobile");o.body.setLinvel({x:steer.x,y:v.y,z:steer.z},true)}world.step();handleImpacts(performance.now());for(const o of orbs){if(!o.alive)continue;const v=o.body.linvel(),cl=clampPlanarSpeed({x:v.x,z:v.z},o.isHuman&&controlModeRef.current==="keys"?"desktop":"mobile");if(cl.x!==v.x||cl.z!==v.z)o.body.setLinvel({x:cl.x,y:v.y,z:cl.z},true);const p=o.body.translation();if(o.airborne&&Math.abs(v.y)<.55&&p.y<3.4)o.airborne=false;if(p.y<-4.5||Math.hypot(p.x,p.z)>config.radius*1.36)eliminate(o,"fell into the void")}acc-=PHYSICS.fixedStep}if(matchElapsed>=config.maxSeconds&&!resolved){const aliveOrbs=orbs.filter(o=>o.alive).sort((a,b)=>b.integrity-a.integrity);aliveOrbs.slice(1).forEach(o=>eliminate(o,"lost sudden death"))}if(ms-lastUi>100){lastUi=ms;setSurvivors(orbs.filter(o=>o.alive).length);setIntegrity(Math.round(human.integrity));setJumpCooldown(clamp((human.jumpReadyAt-performance.now())/config.jumpCooldownMs,0,1))}}
        for(const o of orbs){if(!o.alive)continue;const p=o.body.translation(),q=o.body.rotation();o.mesh.position.set(p.x,p.y,p.z);o.mesh.quaternion.set(q.x,q.y,q.z,q.w);o.label.quaternion.copy(camera.quaternion);const damage=1-o.integrity/100;(o.mesh.material as import("three").MeshPhysicalMaterial).emissiveIntensity=1.05+damage*1.8+Math.sin(ms*.012)*damage*.45;o.core.scale.setScalar(1+damage*.18)}for(let i=shocks.length-1;i>=0;i--){const sh=shocks[i]!,age=ms-sh.born,t=age/sh.life;if(t>=1){scene.remove(sh.mesh);(sh.mesh.geometry as import("three").BufferGeometry).dispose();(sh.mesh.material as import("three").Material).dispose();shocks.splice(i,1)}else{sh.mesh.scale.setScalar(1+t*3.5);(sh.mesh.material as import("three").MeshBasicMaterial).opacity=.42*(1-t)}}
        const focus=human.alive?human:orbs.find(o=>o.alive);if(focus){const p=focus.body.translation(),v=focus.body.linvel(),speed=Math.hypot(v.x,v.z);if(speed>.3)lastFacing.lerp(new THREE.Vector3(v.x,0,v.z).normalize(),.12);const back=mobileish?7.8:6.5,height=mobileish?4.6:3.9;desired.set(p.x-lastFacing.x*back,p.y+height,p.z-lastFacing.z*back);if(cameraShake>.002){desired.x+=(rand()-.5)*cameraShake;desired.y+=(rand()-.5)*cameraShake;desired.z+=(rand()-.5)*cameraShake;cameraShake*=.86}camera.position.lerp(desired,1-Math.exp(-dt*7.2));look.set(p.x+lastFacing.x*(2.0+speed*.15),p.y+.25,p.z+lastFacing.z*(2.0+speed*.15));camera.lookAt(look)}renderer.render(scene,camera)};render(performance.now());
      cleanupThree=()=>{cancelAnimationFrame(frame);ro.disconnect();audio.stop();orbGeo.dispose();coreGeo.dispose();terrainMat.dispose();edgeMat.dispose();renderer.dispose();mount.innerHTML=""};
    })();
    return()=>{cancelled=true;cleanupThree?.();audio.stop();window.removeEventListener("deviceorientation",orientation);window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)};
  },[config,generation,playerCount,seed,style]);

  const touchStart=useCallback((e:React.PointerEvent<HTMLDivElement>)=>e.currentTarget.setPointerCapture(e.pointerId),[]);const touchMove=useCallback((e:React.PointerEvent<HTMLDivElement>)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/(r.width*.36),y=(e.clientY-(r.top+r.height/2))/(r.height*.36),m=Math.max(1,Math.hypot(x,y));controlsRef.current.touchX=clamp(x/m,-1,1);controlsRef.current.touchY=clamp(-y/m,-1,1)},[]);const touchEnd=useCallback((e:React.PointerEvent<HTMLDivElement>)=>{controlsRef.current.touchX=0;controlsRef.current.touchY=0;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}},[]);
  const left=Math.max(0,config.maxSeconds-elapsed);return <div className="arena-sandbox-game arena-course-game"><div ref={mountRef} className="arena-sandbox-canvas"/><div className="arena-hud arena-hud-top"><div><span>ORBS REMAIN</span><strong>{survivors}</strong></div><div className="arena-event"><strong>{eventText}</strong><small>{Math.floor(left/60)}:{String(Math.floor(left%60)).padStart(2,"0")} · integrity {integrity}%</small></div><div><span>INTEGRITY</span><strong>{integrity}</strong></div></div>{phase==="ready"?<div className="arena-center-card"><span>ADMIN ARENA COURSE</span><h3>LAST ORB STANDING</h3><p>Roll the terrain. Build speed. Jump gaps and attacks. Hard impacts damage integrity and make opponents easier to launch.</p><button className="btn-primary" onClick={()=>startRef.current()}>Enter Arena →</button></div>:null}{phase==="countdown"?<div className="arena-countdown">{countdown||"GO"}</div>:null}{(phase==="eliminated"||phase==="finished"||phase==="won")?<div className="arena-result-card"><span>{phase==="eliminated"?"SPECTATING":"MATCH COMPLETE"}</span><h3>{phase==="won"?"YOU WIN":winner?`${winner} WINS`:"YOU'RE OUT"}</h3><p>{phase==="eliminated"?`${survivors} Orbs remain. Stay and watch the course close toward the summit.`:"Last Orb standing takes the prize."}</p></div>:null}{phase==="playing"?<div className="arena-jump-wrap"><button className="arena-jump" onClick={()=>jumpRef.current()} disabled={jumpCooldown>0.02}><span>JUMP</span><i style={{transform:`scaleX(${1-jumpCooldown})`}}/></button></div>:null}{phase==="playing"&&controlMode==="touch"?<div className="game-touch-pad arena-touch" onPointerDown={touchStart} onPointerMove={touchMove} onPointerUp={touchEnd} onPointerCancel={touchEnd}><div className="game-touch-knob"/></div>:null}{sensorAvailable&&phase==="playing"?<div className="arena-controls"><button onClick={()=>void requestMotion()}>{controlMode==="sensor"?"Tilt active":"Enable tilt"}</button>{controlMode==="sensor"?<button onClick={()=>{controlModeRef.current="touch";setControlMode("touch")}}>Touch control</button>:null}</div>:null}<div className="arena-control-hint"><span className="arena-desktop-hint">ARROWS / WASD · ROLL &nbsp;&nbsp; SPACE · JUMP</span><span className="arena-mobile-hint">ROLL · JUMP · USE TERRAIN</span></div></div>;
}
