"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { PHYSICS } from "@/game/constants";
import {
  RACE_RESCUE_MS,
  buildRaceConfig,
  circularPointDistance,
  generateRaceManifest,
  isForwardLapWrap,
  nearestRacePoint,
  raceProgress,
  type RaceItemKind,
} from "@/game/race";
import { RaceAudioEngine } from "@/game/raceAudio";
import type { GameStyle } from "@/game/types";

type Props = { playerCount:number; style:GameStyle; seed:string; generation:number };
type Phase = "ready"|"countdown"|"playing"|"won"|"finished";
type ControlMode = "keys"|"touch";
type Racer = {
  id:string; username:string; color:string; body:import("@dimforge/rapier3d-compat").RigidBody;
  mesh:import("three").Mesh; core:import("three").Mesh; label:import("three").Sprite;
  isHuman:boolean; pointIndex:number; previousPointIndex:number; lap:number; lapArmed:boolean; finishedAt:number|null;
  jumpReadyAt:number; boostUntil:number; slowedUntil:number; item:RaceItemKind|null; pickupReady:Map<string,number>;
  recovering:boolean; rescueStartedAt:number; rescueUntil:number; rescueFrom:import("three").Vector3; rescuePointIndex:number; cloud:import("three").Group;
  botLane:number; botLaneTarget:number; botThinkAt:number; lastHitAt:number;
};
type Missile = { mesh:import("three").Group; owner:Racer; born:number; life:number; position:import("three").Vector3; velocity:import("three").Vector3 };
type Bomb = { mesh:import("three").Group; owner:Racer; born:number; armedAt:number; expiresAt:number; position:import("three").Vector3; hit:Set<string> };

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const names=["orbitaljup","bonkpilot","solsurfer","caturday","mooncrate","zerogravity","mintghost","blockrunner","jupcat","voidwalker","tokenpunk","solanaut","orbmaxi","driftmode","neonape","cryptokite","glasscanon","rollhard","chainchaser","memeengine","jupiterian","vaultfox","orbitron","turbocat","candycloud","solstice","nightmarket","ghostroute","mintcondition","prismcat","warpdrive","moonrail","starfruit","lamportlane","glowworm","supernova","bagrocket","speedfiend","violetcat","solarflare","helioroll","meteormax","orbitkid","stardegen","jupstream","nebular","trackcat","pixelpilot","voidlane"];

function seeded(seed:string){let h=2166136261;for(let i=0;i<seed.length;i++)h=Math.imul(h^seed.charCodeAt(i),16777619);return()=>{h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return(h>>>0)/4294967296}}
function orbColor(i:number,r:()=>number){const hue=(i*137.508+r()*24)%360;return `hsl(${hue.toFixed(0)} 92% 62%)`}
function fmt(seconds:number){const m=Math.floor(seconds/60),s=Math.floor(seconds%60),ms=Math.floor((seconds%1)*100);return `${m}:${String(s).padStart(2,"0")}.${String(ms).padStart(2,"0")}`}

function makeLabel(THREE:typeof import("three"),text:string,tint:string){
  const c=document.createElement("canvas");c.width=512;c.height=128;const x=c.getContext("2d")!;x.font="800 44px Arial";const w=Math.min(460,x.measureText(text).width+62),left=(512-w)/2;
  x.fillStyle="rgba(2,5,16,.72)";x.strokeStyle="rgba(255,255,255,.16)";x.lineWidth=3;x.beginPath();x.roundRect(left,23,w,70,26);x.fill();x.stroke();x.fillStyle=tint;x.beginPath();x.arc(left+28,58,8,0,Math.PI*2);x.fill();x.fillStyle="white";x.textAlign="center";x.fillText(text,256,73);
  const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(3.25,.81,1);return s;
}

function makeOrbMaterial(THREE:typeof import("three"),primary:string,secondary:string,accent:string){
  return new THREE.ShaderMaterial({
    transparent:true,depthWrite:true,
    uniforms:{uTime:{value:0},uPrimary:{value:new THREE.Color(primary)},uSecondary:{value:new THREE.Color(secondary)},uAccent:{value:new THREE.Color(accent)},uSpeed:{value:0}},
    vertexShader:`varying vec3 vObj;varying vec3 vNormalW;varying vec3 vWorld;void main(){vObj=position;vNormalW=normalize(mat3(modelMatrix)*normal);vec4 world=modelMatrix*vec4(position,1.0);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,
    fragmentShader:`precision highp float;varying vec3 vObj;varying vec3 vNormalW;varying vec3 vWorld;uniform float uTime;uniform float uSpeed;uniform vec3 uPrimary;uniform vec3 uSecondary;uniform vec3 uAccent;void main(){vec3 N=normalize(vNormalW);vec3 V=normalize(cameraPosition-vWorld);float fres=pow(1.0-max(dot(N,V),0.0),2.2);float ribbons=sin(vObj.x*12.0+vObj.y*8.0+uTime*.0018)+sin(vObj.z*15.0-vObj.y*9.0-uTime*.0013);float veins=smoothstep(.42,.9,abs(ribbons*.5));vec3 base=mix(uPrimary,uSecondary,.36+.28*sin(vObj.y*8.0+uTime*.001));base=mix(base,uAccent,veins*.28);base+=fres*(uSecondary*.78+vec3(.24));base+=uAccent*clamp(uSpeed/22.0,0.0,1.0)*.34;float alpha=.88+fres*.1;gl_FragColor=vec4(base,alpha);}`
  });
}

function makeTrackMaterial(THREE:typeof import("three"),style:GameStyle){
  return new THREE.ShaderMaterial({
    side:THREE.DoubleSide,depthWrite:true,
    uniforms:{uTime:{value:0},uA:{value:new THREE.Color(style.marble)},uB:{value:new THREE.Color(style.marbleSecondary)},uC:{value:new THREE.Color(style.accent)},uFloor:{value:new THREE.Color(style.floor)}},
    vertexShader:`varying vec2 vUv;varying vec3 vWorld;void main(){vUv=uv;vec4 w=modelMatrix*vec4(position,1.0);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,
    fragmentShader:`precision highp float;varying vec2 vUv;varying vec3 vWorld;uniform float uTime;uniform vec3 uA;uniform vec3 uB;uniform vec3 uC;uniform vec3 uFloor;float s(float x){return sin(x)*.5+.5;}void main(){float t=uTime*.00022;vec2 p=vec2((vUv.x-.5)*7.0,vUv.y*.85);float w1=sin(p.y*1.36+sin(p.x*2.8+t*2.1)*1.35+t*2.4);float w2=sin(p.y*.77-p.x*2.25+sin(p.y*.19-t)*2.0-t*1.55);float w3=sin(length(vec2(p.x*.86,mod(p.y,15.0)-7.5))*1.55-t*2.2);float oil=s(w1*1.15+w2*.92+w3*.62);float topology=s(sin(p.x*5.8+w2*1.7+t*.8)+sin(p.y*.42+w1*1.4));vec3 c=mix(uFloor*.38,uA,oil);c=mix(c,uB,s(w2+w3)*.56);c=mix(c,uC,topology*.42);float filament=smoothstep(.91,.99,sin((oil+topology)*15.0+p.y*.17)*.5+.5);c+=vec3(.36,.55,.8)*filament*.42;float edge=smoothstep(.39,.49,abs(vUv.x-.5));c+=mix(uB,uC,oil)*edge*.18;gl_FragColor=vec4(c,1.0);}`
  });
}

function makeSky(THREE:typeof import("three"),accent:string){
  const g=new THREE.SphereGeometry(330,44,28),m=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{uAccent:{value:new THREE.Color(accent)}},vertexShader:`varying vec3 vDir;void main(){vDir=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec3 vDir;uniform vec3 uAccent;void main(){float h=pow(1.0-abs(vDir.y),5.0);float a=sin(vDir.x*9.0+vDir.z*12.0+vDir.y*5.0)*.5+.5;float aur=smoothstep(.72,1.0,a)*h;vec3 c=mix(vec3(.004,.006,.027),vec3(.018,.028,.095),h);c+=uAccent*h*.22;c+=vec3(.05,.75,.95)*aur*.2;gl_FragColor=vec4(c,1.0);}`});return new THREE.Mesh(g,m);
}

function makeCloud(THREE:typeof import("three"),color:string){
  const g=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false});
  [[0,0,0,.65],[-.55,.02,.08,.44],[.52,.04,.08,.48],[-.2,.16,-.28,.5],[.26,.18,-.25,.53]].forEach(([x,y,z,s])=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.62,12,8),mat);m.position.set(x!,y!,z!);m.scale.setScalar(s!);g.add(m)});g.visible=false;return g;
}

function pointPosition(THREE:typeof import("three"),p:{x:number;y:number;z:number;rightX:number;rightY:number;rightZ:number;width:number},lane=0,y=0){return new THREE.Vector3(p.x+p.rightX*p.width*lane,p.y+p.rightY*p.width*lane+y,p.z+p.rightZ*p.width*lane)}

export default function RaceSandbox({playerCount,style,seed,generation}:Props){
  const mountRef=useRef<HTMLDivElement|null>(null);
  const controlsRef=useRef({left:false,right:false,up:false,down:false,touchX:0});
  const actionRef=useRef<()=>void>(()=>undefined),startRef=useRef<()=>void>(()=>undefined);
  const [phase,setPhase]=useState<Phase>("ready"),[countdown,setCountdown]=useState(0),[elapsed,setElapsed]=useState(0),[lap,setLap]=useState(1),[place,setPlace]=useState(playerCount),[speed,setSpeed]=useState(0),[item,setItem]=useState<RaceItemKind|null>(null),[eventText,setEventText]=useState("RACE"),[controlMode,setControlMode]=useState<ControlMode>("keys"),[rescueLeft,setRescueLeft]=useState(0),[wake,setWake]=useState(false),[winner,setWinner]=useState<string|null>(null);
  const config=useMemo(()=>buildRaceConfig(playerCount),[playerCount]);
  const manifest=useMemo(()=>generateRaceManifest(seed,style,config.trackWidth),[seed,style,config.trackWidth]);

  useEffect(()=>{
    const mount=mountRef.current;if(!mount)return;let cancelled=false,frame=0,cleanupThree:(()=>void)|null=null;const audio=new RaceAudioEngine();
    setPhase("ready");setElapsed(0);setLap(1);setPlace(playerCount);setSpeed(0);setItem(null);setEventText("RACE");setRescueLeft(0);setWake(false);setWinner(null);
    const coarse=window.matchMedia("(pointer: coarse)").matches;if(coarse)setControlMode("touch");
    const onKey=(e:KeyboardEvent,down:boolean)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","KeyW","KeyA","KeyS","KeyD","Space"].includes(e.code))e.preventDefault();if(e.code==="ArrowLeft"||e.code==="KeyA")controlsRef.current.left=down;if(e.code==="ArrowRight"||e.code==="KeyD")controlsRef.current.right=down;if(e.code==="ArrowUp"||e.code==="KeyW")controlsRef.current.up=down;if(e.code==="ArrowDown"||e.code==="KeyS")controlsRef.current.down=down;if(e.code==="Space"&&down&&!e.repeat)actionRef.current()};
    const kd=(e:KeyboardEvent)=>onKey(e,true),ku=(e:KeyboardEvent)=>onKey(e,false);window.addEventListener("keydown",kd,{passive:false});window.addEventListener("keyup",ku,{passive:false});

    (async()=>{
      const [THREE,RAPIER]=await Promise.all([import("three"),import("@dimforge/rapier3d-compat")]);await RAPIER.init();if(cancelled||!mountRef.current)return;
      const mobileish=coarse||window.innerWidth<800;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2("#030513",.0024);const camera=new THREE.PerspectiveCamera(mobileish?66:60,1,.08,620);
      const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobileish?1.15:1.55));renderer.shadowMap.enabled=false;mount.innerHTML="";mount.appendChild(renderer.domElement);
      scene.add(makeSky(THREE,style.accent));scene.add(new THREE.HemisphereLight("#B8D8FF","#071126",1.65));const sun=new THREE.DirectionalLight("#FFFFFF",1.8);sun.position.set(40,90,30);scene.add(sun);

      const starsGeo=new THREE.BufferGeometry(),stars:number[]=[];const rand=seeded(`${seed}:stars`);for(let i=0;i<1750;i++){const r=150+rand()*145,a=rand()*Math.PI*2,u=rand()*2-1,s=Math.sqrt(1-u*u);stars.push(Math.cos(a)*s*r,u*r,Math.sin(a)*s*r)}starsGeo.setAttribute("position",new THREE.Float32BufferAttribute(stars,3));const starsMat=new THREE.PointsMaterial({color:"#DDEBFF",size:.55,transparent:true,opacity:.72,depthWrite:false});scene.add(new THREE.Points(starsGeo,starsMat));
      const planetMat=new THREE.MeshPhysicalMaterial({color:style.marbleSecondary,emissive:style.accent,emissiveIntensity:.35,roughness:.5,metalness:.05});const planet=new THREE.Mesh(new THREE.SphereGeometry(18,32,20),planetMat);planet.position.set(-116,42,-104);scene.add(planet);const ring=new THREE.Mesh(new THREE.TorusGeometry(25,.9,12,64),new THREE.MeshBasicMaterial({color:style.accent,transparent:true,opacity:.35,depthWrite:false}));ring.position.copy(planet.position);ring.rotation.x=1.15;ring.rotation.z=.25;scene.add(ring);

      const verts:number[]=[],uvs:number[]=[],indices:number[]=[];for(const p of manifest.points){const half=p.width/2;verts.push(p.x-p.rightX*half,p.y-p.rightY*half,p.z-p.rightZ*half,p.x+p.rightX*half,p.y+p.rightY*half,p.z+p.rightZ*half);const v=p.distance/manifest.lapLength*18;uvs.push(0,v,1,v)}
      for(let i=0;i<manifest.points.length;i++){const j=(i+1)%manifest.points.length,p=manifest.points[i]!,n=manifest.points[j]!;if(p.gap||n.gap)continue;const a=i*2,b=i*2+1,c=j*2,d=j*2+1;indices.push(a,b,c,b,d,c)}
      const trackGeo=new THREE.BufferGeometry();trackGeo.setAttribute("position",new THREE.Float32BufferAttribute(verts,3));trackGeo.setAttribute("uv",new THREE.Float32BufferAttribute(uvs,2));trackGeo.setIndex(indices);trackGeo.computeVertexNormals();const trackMat=makeTrackMaterial(THREE,style);const track=new THREE.Mesh(trackGeo,trackMat);scene.add(track);
      const edgePositions:number[]=[];for(let i=0;i<manifest.points.length;i++){const j=(i+1)%manifest.points.length,p=manifest.points[i]!,n=manifest.points[j]!;if(p.gap||n.gap)continue;for(const side of [-1,1]){const hp=p.width/2*side,hn=n.width/2*side;edgePositions.push(p.x+p.rightX*hp,p.y+p.rightY*hp+.035,p.z+p.rightZ*hp,n.x+n.rightX*hn,n.y+n.rightY*hn+.035,n.z+n.rightZ*hn)}}const edgeGeo=new THREE.BufferGeometry();edgeGeo.setAttribute("position",new THREE.Float32BufferAttribute(edgePositions,3));const edgeMat=new THREE.LineBasicMaterial({color:style.marbleSecondary,transparent:true,opacity:.82,blending:THREE.AdditiveBlending});scene.add(new THREE.LineSegments(edgeGeo,edgeMat));

      const world=new RAPIER.World({x:0,y:-9.81,z:0});const collider=RAPIER.ColliderDesc.trimesh(new Float32Array(verts),new Uint32Array(indices)).setFriction(1.05).setRestitution(.04);world.createCollider(collider);

      const orientAt=(obj:import("three").Object3D,pointIndex:number)=>{const p=manifest.points[pointIndex]!;const tangent=new THREE.Vector3(p.tangentX,p.tangentY,p.tangentZ).normalize(),right=new THREE.Vector3(p.rightX,p.rightY,p.rightZ).normalize();right.addScaledVector(tangent,-right.dot(tangent)).normalize();const up=new THREE.Vector3().crossVectors(tangent,right).normalize();const m=new THREE.Matrix4().makeBasis(right,up,tangent);obj.quaternion.setFromRotationMatrix(m)};

      const boostMeshes:import("three").Mesh[]=[];for(const b of manifest.boosts){const p=manifest.points[b.pointIndex]!,m=new THREE.Mesh(new THREE.BoxGeometry(p.width*.31,.055,2.5),new THREE.MeshBasicMaterial({color:style.marbleSecondary,transparent:true,opacity:.78,blending:THREE.AdditiveBlending}));m.position.copy(pointPosition(THREE,p,b.lane,.07));orientAt(m,b.pointIndex);scene.add(m);boostMeshes.push(m)}
      const rampMeshes:import("three").Mesh[]=[];for(const r of manifest.ramps){const p=manifest.points[r.pointIndex]!,width=p.width*.32,length=3.7,height=.38,m=new THREE.Mesh(new THREE.BoxGeometry(width,height,length),new THREE.MeshPhysicalMaterial({color:style.accent,emissive:style.marbleSecondary,emissiveIntensity:1.0,roughness:.18,metalness:.25,clearcoat:1}));m.position.copy(pointPosition(THREE,p,r.lane,.20));orientAt(m,r.pointIndex);m.rotateX(-.13);scene.add(m);m.updateMatrixWorld(true);const wp=new THREE.Vector3(),wq=new THREE.Quaternion(),ws=new THREE.Vector3();m.matrixWorld.decompose(wp,wq,ws);world.createCollider(RAPIER.ColliderDesc.cuboid(width/2,height/2,length/2).setTranslation(wp.x,wp.y,wp.z).setRotation({x:wq.x,y:wq.y,z:wq.z,w:wq.w}).setFriction(1.08).setRestitution(.04));rampMeshes.push(m)}
      const launchP=manifest.points[manifest.plungeLaunchIndex]!,launchRampWidth=launchP.width*.92,launchRampLength=9.0,launchRampHeight=.48;const launchRamp=new THREE.Mesh(new THREE.BoxGeometry(launchRampWidth,launchRampHeight,launchRampLength),new THREE.MeshPhysicalMaterial({color:style.marbleSecondary,emissive:style.accent,emissiveIntensity:1.9,roughness:.08,metalness:.35,clearcoat:1}));launchRamp.position.copy(pointPosition(THREE,launchP,0,.24));orientAt(launchRamp,manifest.plungeLaunchIndex);launchRamp.rotateX(-.26);scene.add(launchRamp);launchRamp.updateMatrixWorld(true);{const wp=new THREE.Vector3(),wq=new THREE.Quaternion(),ws=new THREE.Vector3();launchRamp.matrixWorld.decompose(wp,wq,ws);world.createCollider(RAPIER.ColliderDesc.cuboid(launchRampWidth/2,launchRampHeight/2,launchRampLength/2).setTranslation(wp.x,wp.y,wp.z).setRotation({x:wq.x,y:wq.y,z:wq.z,w:wq.w}).setFriction(1.12).setRestitution(.03))}
      const pickupGroups:import("three").Group[]=[];for(const pick of manifest.pickups){const p=manifest.points[pick.pointIndex]!,g=new THREE.Group();const color=pick.kind==="missile"?"#FF9A3C":"#FF4D72";const torus=new THREE.Mesh(new THREE.TorusGeometry(.72,.085,10,36),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.92,blending:THREE.AdditiveBlending,depthWrite:false}));torus.rotation.y=Math.PI/2;g.add(torus);const dot=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),new THREE.MeshBasicMaterial({color:"#FFFFFF"}));dot.position.z=.02;g.add(dot);g.position.copy(pointPosition(THREE,p,pick.lane,1.05));orientAt(g,pick.pointIndex);scene.add(g);pickupGroups.push(g)}

      const finishP=manifest.points[0]!,finish=new THREE.Group();const gateMat=new THREE.MeshBasicMaterial({color:style.accent,transparent:true,opacity:.75,blending:THREE.AdditiveBlending});for(const side of [-1,1]){const post=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,4.8,12),gateMat);post.position.set(finishP.width*.48*side,2.35,0);finish.add(post)}const bar=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,finishP.width*.96,12),gateMat);bar.rotation.z=Math.PI/2;bar.position.y=4.7;finish.add(bar);finish.position.set(finishP.x,finishP.y,finishP.z);orientAt(finish,0);scene.add(finish);

      const orbGeo=new THREE.SphereGeometry(PHYSICS.ballRadius,40,28),coreGeo=new THREE.SphereGeometry(PHYSICS.ballRadius*.66,28,18);const racers:Racer[]=[];
      const spawnP=manifest.points[0]!,spawnT=new THREE.Vector3(spawnP.tangentX,0,spawnP.tangentZ).normalize(),spawnR=new THREE.Vector3(spawnP.rightX,spawnP.rightY,spawnP.rightZ).normalize();
      for(let i=0;i<playerCount;i++){
        const human=i===0,row=Math.floor(i/7),col=i%7,lane=(col-3)/3.4,back=row*1.55+1.2;const x=spawnP.x+spawnR.x*lane*spawnP.width*.43-spawnT.x*back,z=spawnP.z+spawnR.z*lane*spawnP.width*.43-spawnT.z*back,y=spawnP.y+1.0+spawnR.y*lane*spawnP.width*.43;
        const color=human?style.marble:orbColor(i,rand),secondary=human?style.marbleSecondary:color;const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,y,z).setLinearDamping(.18).setAngularDamping(.16).setCcdEnabled(true));world.createCollider(RAPIER.ColliderDesc.ball(PHYSICS.ballRadius).setDensity(1).setFriction(1.08).setRestitution(.12),body);
        const mat=makeOrbMaterial(THREE,color,secondary,style.accent),mesh=new THREE.Mesh(orbGeo,mat),core=new THREE.Mesh(coreGeo,new THREE.MeshBasicMaterial({color:secondary,transparent:true,opacity:.24,blending:THREE.AdditiveBlending,depthWrite:false}));mesh.add(core);const label=makeLabel(THREE,human?"@you":`@${names[(i-1)%names.length]}`,color);label.position.set(0,1.03,0);mesh.add(label);scene.add(mesh);const cloud=makeCloud(THREE,secondary);scene.add(cloud);
        racers.push({id:`racer-${i}`,username:human?"@you":`@${names[(i-1)%names.length]}`,color,body,mesh,core,label,isHuman:human,pointIndex:0,previousPointIndex:0,lap:0,lapArmed:false,finishedAt:null,jumpReadyAt:0,boostUntil:0,slowedUntil:0,item:null,pickupReady:new Map(),recovering:false,rescueStartedAt:0,rescueUntil:0,rescueFrom:new THREE.Vector3(),rescuePointIndex:0,cloud,botLane:lane,botLaneTarget:lane,botThinkAt:0,lastHitAt:0});
      }
      const human=racers[0]!;
      const missiles:Missile[]=[],bombs:Bomb[]=[];const missileGeo=new THREE.SphereGeometry(.19,10,8),missileMat=new THREE.MeshBasicMaterial({color:"#FF9A3C",transparent:true,opacity:.96,blending:THREE.AdditiveBlending});const bombGeo=new THREE.SphereGeometry(.31,12,9),bombMat=new THREE.MeshBasicMaterial({color:"#28020A"}),bombRingGeo=new THREE.TorusGeometry(.6,.055,8,28),bombRingMat=new THREE.MeshBasicMaterial({color:"#FF4D72",transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false});
      const makeMissile=()=>{const g=new THREE.Group();const m=new THREE.Mesh(missileGeo,missileMat);g.add(m);const tail=new THREE.Mesh(new THREE.ConeGeometry(.13,.65,8),missileMat);tail.rotation.x=-Math.PI/2;tail.position.z=.38;g.add(tail);scene.add(g);return g};
      const makeBomb=()=>{const g=new THREE.Group();const m=new THREE.Mesh(bombGeo,bombMat),r=new THREE.Mesh(bombRingGeo,bombRingMat);r.rotation.x=Math.PI/2;g.add(m,r);scene.add(g);return g};
      const hitRacer=(target:Racer,attacker:Racer,now:number,power=1)=>{if(target.recovering||target.finishedAt||now-target.lastHitAt<420)return;target.lastHitAt=now;const tp=target.body.translation(),ap=attacker.body.translation(),dx=tp.x-ap.x,dz=tp.z-ap.z,mag=Math.hypot(dx,dz)||1;target.body.applyImpulse({x:dx/mag*1.45*power,y:.8*power,z:dz/mag*1.45*power},true);const v=target.body.linvel();target.body.setLinvel({x:v.x*.64,y:v.y,z:v.z*.64},true);target.slowedUntil=now+760;if(target.isHuman){setEventText("HIT · HOLD YOUR LINE");audio.hit()}};
      const useWeapon=(o:Racer,now:number)=>{const kind=o.item;if(!kind)return;const p=o.body.translation(),rp=manifest.points[o.pointIndex]!,forward=new THREE.Vector3(rp.tangentX,Math.max(-.05,rp.tangentY*.35),rp.tangentZ).normalize();if(kind==="missile"){const mesh=makeMissile(),pos=new THREE.Vector3(p.x,p.y+.12,p.z).addScaledVector(forward,1.0);mesh.position.copy(pos);missiles.push({mesh,owner:o,born:now,life:1900,position:pos,velocity:forward.multiplyScalar(25.5)});if(o.isHuman){audio.missile();setEventText("PULSE LANCE · FIRED")}}else{const mesh=makeBomb(),pos=new THREE.Vector3(p.x,p.y-.2,p.z).addScaledVector(forward,-1.25);mesh.position.copy(pos);bombs.push({mesh,owner:o,born:now,armedAt:now+620,expiresAt:now+9000,position:pos,hit:new Set()});if(o.isHuman){audio.bomb();setEventText("BOMB · DROPPED")}}o.item=null;if(o.isHuman)setItem(null)};
      const grounded=(o:Racer)=>{if(o.recovering)return false;const p=o.body.translation(),rp=manifest.points[o.pointIndex]!,v=o.body.linvel();return !rp.gap&&Math.abs(p.y-rp.y)<1.55&&Math.abs(v.y)<2.4};
      const jump=(o:Racer,now:number)=>{if(now<o.jumpReadyAt||!grounded(o))return false;const v=o.body.linvel();o.body.setLinvel({x:v.x,y:Math.max(v.y,config.jumpImpulse),z:v.z},true);o.jumpReadyAt=now+config.jumpCooldownMs;if(o.isHuman)audio.jump();return true};
      const action=(o:Racer)=>{if(phaseRef.current!=="playing"||o.recovering||o.finishedAt)return;const now=performance.now();jump(o,now);useWeapon(o,now)};actionRef.current=()=>action(human);

      let live=false,resolved=false,matchStart=0,lastUi=0,acc=0,prev=performance.now(),simTime=0;const phaseRef={current:"ready" as Phase};
      const setRacePhase=(p:Phase)=>{phaseRef.current=p;setPhase(p)};
      startRef.current=()=>{if(phaseRef.current!=="ready")return;void audio.start();setRacePhase("countdown");let n=3;setCountdown(n);const id=window.setInterval(()=>{n-=1;if(n>0){setCountdown(n);return}window.clearInterval(id);setCountdown(0);setEventText("GO!");setRacePhase("playing");matchStart=performance.now();live=true;for(const o of racers){const rp=manifest.points[o.pointIndex]!,v=new THREE.Vector3(rp.tangentX,0,rp.tangentZ).normalize().multiplyScalar(config.baseSpeed*.72);o.body.setLinvel({x:v.x,y:0,z:v.z},true)}},760)};

      const beginRescue=(o:Racer,now:number)=>{if(o.recovering||o.finishedAt)return;o.recovering=true;o.rescueStartedAt=now;o.rescueUntil=now+RACE_RESCUE_MS;const p=o.body.translation();o.rescueFrom.set(p.x,p.y,p.z);o.rescuePointIndex=(o.pointIndex-7+manifest.points.length)%manifest.points.length;o.body.setEnabled(false);if(o.isHuman){audio.rescue();setEventText("NIMBUS RESCUE · 3 SECONDS")}};
      const finishRescue=(o:Racer)=>{const rp=manifest.points[o.rescuePointIndex]!,safe=pointPosition(THREE,rp,0,1.05);o.body.setTranslation({x:safe.x,y:safe.y,z:safe.z},false);o.body.setRotation({x:0,y:0,z:0,w:1},false);o.body.setEnabled(true);o.body.setLinvel({x:rp.tangentX*config.baseSpeed*.72,y:0,z:rp.tangentZ*config.baseSpeed*.72},true);o.pointIndex=rp.index;o.previousPointIndex=rp.index;o.recovering=false;o.cloud.visible=false};

      const updateItems=(o:Racer,now:number)=>{if(o.recovering||o.finishedAt)return;if(circularPointDistance(o.pointIndex,manifest.plungeLaunchIndex,manifest.points.length)<=3&&(o.pickupReady.get("plunge-launch")||0)<=now){o.pickupReady.set("plunge-launch",now+2400);o.boostUntil=Math.max(o.boostUntil,now+1450);if(o.isHuman){audio.boost();setEventText("ORBITAL PLUNGE · SEND IT")}}for(const ramp of manifest.ramps){if(circularPointDistance(o.pointIndex,ramp.pointIndex,manifest.points.length)>2)continue;if((o.pickupReady.get(ramp.id)||0)>now)continue;const rp=manifest.points[o.pointIndex]!,p=o.body.translation(),center=pointPosition(THREE,rp,ramp.lane,0);if(Math.hypot(p.x-center.x,p.z-center.z)>rp.width*.24)continue;o.pickupReady.set(ramp.id,now+1800);o.boostUntil=Math.max(o.boostUntil,now+720);if(o.isHuman){audio.boost();setEventText("RAMP CHARGE · FLY")}}for(const [i,b] of manifest.boosts.entries()){if(circularPointDistance(o.pointIndex,b.pointIndex,manifest.points.length)>2)continue;if((o.pickupReady.get(b.id)||0)>now)continue;const rp=manifest.points[o.pointIndex]!,p=o.body.translation(),center=pointPosition(THREE,rp,b.lane,0),lateral=Math.hypot(p.x-center.x,p.z-center.z);if(lateral>rp.width*.22)continue;o.pickupReady.set(b.id,now+1600);o.boostUntil=now+1250;if(o.isHuman){audio.boost();setEventText("SPEED CHARGE")}}if(o.item)return;for(const pick of manifest.pickups){if(circularPointDistance(o.pointIndex,pick.pointIndex,manifest.points.length)>2)continue;if((o.pickupReady.get(pick.id)||0)>now)continue;const rp=manifest.points[o.pointIndex]!,p=o.body.translation(),center=pointPosition(THREE,rp,pick.lane,1),d=Math.hypot(p.x-center.x,p.z-center.z);if(d>rp.width*.24)continue;o.item=pick.kind;o.pickupReady.set(pick.id,now+5000);if(o.isHuman){setItem(pick.kind);audio.pickup();setEventText(pick.kind==="missile"?"PULSE LANCE · SPACE JUMP + FIRE":"BOMB · SPACE JUMP + DROP")}break}};

      const botSteer=(o:Racer,now:number)=>{if(now>=o.botThinkAt){const rank=racers.filter(r=>!r.finishedAt).sort((a,b)=>raceProgress(b.pointIndex,b.lap,manifest.points.length)-raceProgress(a.pointIndex,a.lap,manifest.points.length)).indexOf(o);const desperation=clamp(rank/Math.max(1,playerCount-1),0,1);o.botLaneTarget=clamp(o.botLaneTarget+(rand()-.5)*(.34+desperation*.18),-.68,.68);if(rand()<.16)o.botLaneTarget=(rand()-.5)*1.25;o.botThinkAt=now+420+rand()*650;if(o.item&&rand()<.32)action(o);else if(rand()<.055)jump(o,now)}o.botLane+=(o.botLaneTarget-o.botLane)*.028;return clamp(o.botLane*1.22,-1,1)};

      const updateProjectiles=(now:number,dt:number)=>{for(let i=missiles.length-1;i>=0;i--){const m=missiles[i]!,age=now-m.born;if(age>m.life){scene.remove(m.mesh);missiles.splice(i,1);continue}m.position.addScaledVector(m.velocity,dt);m.mesh.position.copy(m.position);m.mesh.lookAt(m.position.clone().add(m.velocity));let hit=false;for(const o of racers){if(o===m.owner||o.recovering||o.finishedAt)continue;const p=o.body.translation();if(Math.hypot(p.x-m.position.x,p.y-m.position.y,p.z-m.position.z)<.85){hitRacer(o,m.owner,now,1);hit=true;break}}if(hit){scene.remove(m.mesh);missiles.splice(i,1);continue}const near=nearestRacePoint(manifest.points,m.position.x,m.position.y,m.position.z);if(near.distanceSq>24*24){scene.remove(m.mesh);missiles.splice(i,1)}}for(let i=bombs.length-1;i>=0;i--){const b=bombs[i]!;b.mesh.rotation.y+=dt*1.8;(b.mesh.children[1] as import("three").Mesh).rotation.z+=dt*2.5;if(now>=b.expiresAt){scene.remove(b.mesh);bombs.splice(i,1);continue}if(now<b.armedAt)continue;for(const o of racers){if(o===b.owner||o.recovering||o.finishedAt||b.hit.has(o.id))continue;const p=o.body.translation();if(Math.hypot(p.x-b.position.x,p.z-b.position.z)<1.45&&Math.abs(p.y-b.position.y)<2.0){b.hit.add(o.id);hitRacer(o,b.owner,now,1.18);b.expiresAt=Math.min(b.expiresAt,now+120)}}}};

      const rankOf=(target:Racer)=>{const ordered=[...racers].sort((a,b)=>{if(a.finishedAt&&b.finishedAt)return a.finishedAt-b.finishedAt;if(a.finishedAt)return -1;if(b.finishedAt)return 1;return raceProgress(b.pointIndex,b.lap,manifest.points.length)-raceProgress(a.pointIndex,a.lap,manifest.points.length)});return ordered.indexOf(target)+1};
      const updateDraft=(now:number)=>{let active=false;const hp=human.body.translation(),hprog=raceProgress(human.pointIndex,human.lap,manifest.points.length);for(const o of racers){if(o===human||o.finishedAt||o.recovering)continue;const d=raceProgress(o.pointIndex,o.lap,manifest.points.length)-hprog;if(d<=0||d>6)continue;const p=o.body.translation();if(Math.hypot(p.x-hp.x,p.z-hp.z)<7.8){active=true;human.boostUntil=Math.max(human.boostUntil,now+260);break}}setWake(active)};

      const resize=()=>{const r=mount.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(mount);resize();renderer.compile(scene,camera);renderer.render(scene,camera);
      const camPos=new THREE.Vector3(),camLook=new THREE.Vector3(),forward=new THREE.Vector3(),rightV=new THREE.Vector3(),desired=new THREE.Vector3();
      const render=(ms:number)=>{if(cancelled)return;frame=requestAnimationFrame(render);const dt=Math.min(.05,(ms-prev)/1000);prev=ms;(trackMat.uniforms.uTime.value as number)=ms;ring.rotation.y+=dt*.018;finish.rotation.z+=dt*.02;for(let i=0;i<pickupGroups.length;i++){pickupGroups[i]!.rotation.z+=dt*.65;pickupGroups[i]!.position.y+=Math.sin(ms*.002+i)*.0008}for(const b of boostMeshes)b.material instanceof THREE.MeshBasicMaterial&&(b.material.opacity=.62+Math.sin(ms*.006+b.position.x)*.18);
        if(live){const now=performance.now(),elapsedNow=(now-matchStart)/1000;acc+=dt;while(acc>=PHYSICS.fixedStep){simTime+=PHYSICS.fixedStep;for(const o of racers){if(o.finishedAt)continue;if(o.recovering){if(now>=o.rescueUntil)finishRescue(o);continue}const p=o.body.translation(),nearest=nearestRacePoint(manifest.points,p.x,p.y,p.z,o.pointIndex),rp=nearest.point;o.previousPointIndex=o.pointIndex;o.pointIndex=rp.index;if(o.pointIndex>manifest.points.length*.24)o.lapArmed=true;if(o.lapArmed&&isForwardLapWrap(o.previousPointIndex,o.pointIndex,manifest.points.length)){o.lap+=1;o.lapArmed=false;if(o.isHuman){audio.lap();setLap(Math.min(config.laps,o.lap+1));setEventText(o.lap>=config.laps-1?"FINAL LAP":"LAP COMPLETE")};if(o.lap>=config.laps){o.finishedAt=now;o.body.setLinvel({x:0,y:o.body.linvel().y,z:0},true);if(!resolved){resolved=true;setWinner(o.username);if(o.isHuman){setRacePhase("won");audio.victory()}else setEventText(`${o.username} WINS · FINISH YOUR RACE`)}else if(o.isHuman){setRacePhase("finished")}continue}}
          const trackDistance=Math.sqrt(nearest.distanceSq),fallThreshold=rp.y-8.5;if(p.y<fallThreshold||trackDistance>rp.width*2.25){beginRescue(o,now);continue}
          updateItems(o,now);const k=controlsRef.current;const steer=o.isHuman?(coarse?k.touchX:(k.left?-1:0)+(k.right?1:0)):botSteer(o,now);const v=o.body.linvel(),air=!grounded(o),slow=now<o.slowedUntil ? .72 : 1,boost=now<o.boostUntil;let targetSpeed=boost?config.boostSpeed:config.baseSpeed;targetSpeed+=Math.max(0,-rp.tangentY)*13;if(o.isHuman&&k.up)targetSpeed*=1.07;if(o.isHuman&&k.down)targetSpeed*=.70;targetSpeed*=slow;forward.set(rp.tangentX,0,rp.tangentZ).normalize();rightV.set(rp.rightX,0,rp.rightZ).normalize();desired.copy(forward).multiplyScalar(1).addScaledVector(rightV,steer*config.steeringStrength).normalize();const currentSpeed=Math.hypot(v.x,v.z),response=air?.055:.12,desiredSpeed=clamp(targetSpeed,5,boost?config.boostSpeed:config.maxSpeed+Math.max(0,-rp.tangentY)*12);const tx=desired.x*desiredSpeed,tz=desired.z*desiredSpeed;let nx=v.x+(tx-v.x)*response,nz=v.z+(tz-v.z)*response;if(currentSpeed>desiredSpeed*1.08){const f=desiredSpeed/currentSpeed;nx*=f;nz*=f}o.body.setLinvel({x:nx,y:v.y,z:nz},true)}world.step();updateProjectiles(now,PHYSICS.fixedStep);acc-=PHYSICS.fixedStep}updateDraft(now);if(ms-lastUi>90){lastUi=ms;const v=human.body.linvel();setElapsed(elapsedNow);setSpeed(Math.hypot(v.x,v.z));setPlace(rankOf(human));setItem(human.item);if(human.recovering)setRescueLeft(Math.max(0,(human.rescueUntil-now)/1000));else setRescueLeft(0);audio.setSpeed(Math.hypot(v.x,v.z))}}
        for(const o of racers){const mat=o.mesh.material as import("three").ShaderMaterial;mat.uniforms.uTime.value=ms;if(o.recovering){const t=clamp((ms-o.rescueStartedAt)/RACE_RESCUE_MS,0,1),rp=manifest.points[o.rescuePointIndex]!,end=pointPosition(THREE,rp,0,1.25),arc=Math.sin(t*Math.PI)*5.2;o.mesh.position.lerpVectors(o.rescueFrom,end,t);o.mesh.position.y+=arc;o.cloud.visible=true;o.cloud.position.copy(o.mesh.position);o.cloud.position.y-=.68;o.cloud.rotation.y+=dt*1.2;o.label.quaternion.copy(camera.quaternion);continue}o.cloud.visible=false;const p=o.body.translation(),q=o.body.rotation(),v=o.body.linvel(),sp=Math.hypot(v.x,v.z);o.mesh.position.set(p.x,p.y,p.z);o.mesh.quaternion.set(q.x,q.y,q.z,q.w);o.label.quaternion.copy(camera.quaternion);mat.uniforms.uSpeed.value=sp;o.core.scale.setScalar(1+clamp((sp-config.baseSpeed)/12,0,.22))}
        const hv=human.body.linvel(),hs=Math.hypot(hv.x,hv.z),hp=human.recovering?human.mesh.position:human.body.translation(),rp=manifest.points[human.pointIndex]!;forward.set(rp.tangentX,0,rp.tangentZ).normalize();const back=mobileish?10.5:9.3,height=mobileish?5.6:5.0;desired.set(hp.x-forward.x*back,hp.y+height,hp.z-forward.z*back);camPos.lerp(desired,1-Math.exp(-dt*7));camera.position.copy(camPos);camLook.set(hp.x+forward.x*(4.4+hs*.28),hp.y+.45+Math.max(0,rp.tangentY)*1.8,hp.z+forward.z*(4.4+hs*.28));camera.lookAt(camLook);camera.fov+=(clamp(58+(hs-config.baseSpeed)*1.18,58,72)-camera.fov)*.055;camera.updateProjectionMatrix();renderer.render(scene,camera)};
      camPos.copy(pointPosition(THREE,spawnP,0,6)).addScaledVector(spawnT,-10);render(performance.now());
      cleanupThree=()=>{cancelAnimationFrame(frame);ro.disconnect();audio.stop();scene.traverse((obj:import("three").Object3D)=>{if(obj instanceof THREE.Mesh||obj instanceof THREE.LineSegments||obj instanceof THREE.Points){const geo=(obj as import("three").Mesh).geometry;geo?.dispose?.();const material=(obj as import("three").Mesh).material;if(Array.isArray(material))material.forEach(m=>m.dispose());else material?.dispose?.()}});renderer.dispose();mount.innerHTML=""};
    })();
    return()=>{cancelled=true;cleanupThree?.();audio.stop();window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)};
  },[config,manifest,playerCount,seed,style,generation]);

  const touchStart=useCallback((e:React.PointerEvent<HTMLDivElement>)=>e.currentTarget.setPointerCapture(e.pointerId),[]);
  const touchMove=useCallback((e:React.PointerEvent<HTMLDivElement>)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/(r.width*.42);controlsRef.current.touchX=clamp(x,-1,1)},[]);
  const touchEnd=useCallback((e:React.PointerEvent<HTMLDivElement>)=>{controlsRef.current.touchX=0;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}},[]);
  const itemLabel=item==="missile"?"PULSE":item==="bomb"?"BOMB":"EMPTY";

  return <div className="race-sandbox-game">
    <div ref={mountRef} className="race-sandbox-canvas"/>
    <div className="race-hud race-hud-top">
      <div><span>PLACE</span><strong>{place}<small>/{playerCount}</small></strong></div>
      <div className="race-event"><strong>{eventText}</strong><small>{fmt(elapsed)} · {Math.round(speed*3.6)} KM/H</small></div>
      <div><span>LAP</span><strong>{lap}<small>/3</small></strong></div>
    </div>
    <div className="race-item-hud"><span>ITEM</span><strong className={item?"loaded":""}>{itemLabel}</strong>{wake?<em>ORB WAKE</em>:null}</div>
    {rescueLeft>0?<div className="race-rescue-hud"><strong>NIMBUS RESCUE</strong><span>{rescueLeft.toFixed(1)}s</span></div>:null}
    {phase==="ready"?<div className="arena-center-card race-center-card"><span>ADMIN ONLY · LOCAL LAB</span><h3>RACE</h3><p>Three laps on a never-before-seen Orbital Prismway. Your Orb drives itself: steer the line, draft other racers, hit speed charges, jump whenever you want, and use Space to jump + fire/drop a held weapon.</p><button className="btn-primary" onClick={()=>startRef.current()}>Start race test →</button></div>:null}
    {phase==="countdown"?<div className="arena-countdown race-countdown">{countdown||"GO"}</div>:null}
    {(phase==="won"||phase==="finished")?<div className="arena-result-card race-result-card"><span>RACE COMPLETE</span><h3>{phase==="won"?"YOU WIN":winner?`${winner} WINS`:"FINISHED"}</h3><p>Three laps complete. First valid finisher would own the authoritative prize result in production.</p></div>:null}
    {phase==="playing"?<div className="arena-jump-wrap race-action-wrap"><button className={`arena-jump race-action ${item?"armed":""}`} onClick={()=>actionRef.current()}><span>{item?`JUMP + ${item==="missile"?"FIRE":"DROP"}`:"JUMP"}</span></button></div>:null}
    {phase==="playing"&&controlMode==="touch"?<div className="race-touch" onPointerDown={touchStart} onPointerMove={touchMove} onPointerUp={touchEnd} onPointerCancel={touchEnd}><i style={{transform:`translateX(${controlsRef.current.touchX*28}px)`}}/></div>:null}
    <div className="arena-control-hint race-control-hint"><span className="arena-desktop-hint">A / D OR ← / → · STEER &nbsp;&nbsp; W · TUCK &nbsp;&nbsp; S · BRAKE &nbsp;&nbsp; SPACE · JUMP{item?" + USE ITEM":""}</span><span className="arena-mobile-hint">STEER · JUMP{item?" + USE ITEM":""} · DRAFT · BOOST · 3 LAPS</span></div>
  </div>;
}
