"use client";

import { useMemo, useRef, useState } from "react";
import RaceSandbox from "@/components/game/RaceSandbox";
import { GAME_STYLE_PRESETS } from "@/game/constants";
import { buildRaceConfig, generateRaceManifest } from "@/game/race";
import type { GameStyle } from "@/game/types";

type CaptureFormat="landscape"|"square"|"portrait";
type Draft=GameStyle&{seed:string;playerCount:number};
type Active=Draft&{generation:number};
const HEX=/^#[0-9a-fA-F]{6}$/;
const EMPTY:Draft={seed:"",playerCount:24,marble:"#5B5CF6",marbleSecondary:"#20E3D2",walls:"#20E3D2",floor:"#071126",accent:"#9A5CFF"};

function randomSeed(){const b=new Uint8Array(8);crypto.getRandomValues(b);return Array.from(b,v=>v.toString(16).padStart(2,"0")).join("")}
function randomStyle():GameStyle{const hue=Math.floor(Math.random()*360),h=(n:number)=>`hsl(${(hue+n)%360} 90% 60%)`,hex=(css:string)=>{const c=document.createElement("canvas").getContext("2d")!;c.fillStyle=css;return c.fillStyle.toUpperCase()};return{marble:hex(h(0)),marbleSecondary:hex(h(52)),walls:hex(h(122)),floor:"#030513",accent:hex(h(210))}}

export default function AdminRaceSandbox(){
  const [draft,setDraft]=useState<Draft>(EMPTY),[active,setActive]=useState<Active|null>(null),[format,setFormat]=useState<CaptureFormat>("landscape");const captureRef=useRef<HTMLDivElement|null>(null);
  const ready=[draft.marble,draft.marbleSecondary,draft.walls,draft.floor,draft.accent].every(v=>HEX.test(v))&&draft.seed.trim().length>=2;
  const preview=useMemo(()=>{if(!ready)return null;const config=buildRaceConfig(draft.playerCount);return generateRaceManifest(draft.seed.trim(),draft,config.trackWidth)},[draft,ready]);
  const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(c=>({...c,[key]:value}));const load=(style:GameStyle)=>setDraft(c=>({...c,...style}));const randomize=()=>setDraft(c=>({...c,...randomStyle(),seed:randomSeed()}));const generate=()=>{if(ready)setActive({...draft,seed:draft.seed.trim(),generation:Date.now()})};const fullscreen=async()=>{try{await captureRef.current?.requestFullscreen?.({navigationUI:"hide"})}catch{}};
  return <section className="admin-game-sandbox admin-race-sandbox">
    <div className="admin-sandbox-heading"><div><span className="eyebrow">Third-game laboratory</span><h2>RACE · Orbital Prismway</h2><p>Admin-only local prototype for the new 2–50 player roller race. Procedural 3D track, GPU oil-swirled pavement, hold-to-accelerate controls, free jumping, physical racer collisions, speed charges, Orb Wake drafting, bombs, skill-shot Pulse Lances, the Orbital Plunge and exact three-second Nimbus recovery all live here before any production Orb type is touched.</p></div><span className="admin-sandbox-local">ADMIN ONLY · ISOLATED RACE V2</span></div>
    <div className="admin-sandbox-builder card">
      <div className="admin-sandbox-section"><span className="admin-sandbox-label">01 · Race population + world seed</span><div className="arena-builder-population race-builder-population"><label><span>Racers / Orbs</span><input type="range" min="2" max="50" step="1" value={draft.playerCount} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>update("playerCount",Number(e.target.value))}/><strong>{draft.playerCount}</strong></label><div className="arena-scale-readout"><span>Laps</span><strong>3</strong><small>Target production pacing: roughly three minutes total after tuning.</small></div><div className="arena-scale-readout"><span>Grid</span><strong>7-wide</strong><small>Front-to-back order is the future waiting-room presence priority.</small></div></div><div className="admin-sandbox-seed-row"><label><span>Secret course seed</span><input value={draft.seed} maxLength={48} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>update("seed",e.target.value.replace(/[^a-zA-Z0-9_-]/g,""))} placeholder="e.g. caturday-prism-01"/></label><button type="button" className="btn-secondary" onClick={()=>update("seed",randomSeed())}>Random seed</button></div>{preview?<div className="race-manifest-readout"><span>{Math.round(preview.lapLength)}m / lap</span><span>{preview.points.length} spline samples</span><span>7 speed charges</span><span>3 jump ramps</span><span>6 weapon gates</span><span>1 Orbital Plunge</span><span>{Math.round(Math.min(...preview.points.map(p=>p.width)))}–{Math.round(Math.max(...preview.points.map(p=>p.width)))}m road width</span></div>:null}</div>
      <div className="admin-sandbox-section"><span className="admin-sandbox-label">02 · Prismway palette</span><p className="arena-builder-note">The road uses a tiny animated fragment shader rather than CPU-deforming geometry: psychedelic oil currents slide through the pavement while the actual physics collider remains perfectly static and deterministic.</p><div className="admin-sandbox-presets">{GAME_STYLE_PRESETS.map(p=><button type="button" key={p.name} onClick={()=>load(p.style)}>{p.name}</button>)}<button type="button" onClick={randomize}>Surprise me ✦</button></div><div className="admin-sandbox-colors">{([ ["marble","Your Orb"],["marbleSecondary","Orb / road energy"],["walls","Track structures"],["floor","Oil base"],["accent","Prism energy"] ] as const).map(([key,label])=><label key={key}><span>{label}</span><div className="admin-sandbox-color-control"><input type="color" value={HEX.test(draft[key])?draft[key]:"#5B5CF6"} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>update(key,e.target.value.toUpperCase())}/><input value={draft[key]} maxLength={7} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>update(key,e.target.value.toUpperCase())}/></div></label>)}</div></div>
      <div className="admin-sandbox-section race-rules-strip"><span className="admin-sandbox-label">03 · V2 rules locked into this laboratory</span><div><b>THROTTLE</b><span>Hold W / ↑ (or GO on touch) to accelerate. Release and the Orb naturally sheds speed.</span></div><div><b>SPACE</b><span>Always attempts a jump. If an item is loaded, the same press jumps + uses it.</span></div><div><b>FALL</b><span>Nimbus owns you for exactly 3.0 seconds, then returns you behind legitimate progress.</span></div><div><b>WAKE</b><span>Draft closely behind another Orb for a short natural speed advantage—no hidden rubber-banding.</span></div><div><b>WEAPONS</b><span>Bombs disrupt a line; Pulse Lance is straight-line aim only. Neither is homing.</span></div></div>
      <div className="admin-sandbox-section admin-sandbox-output-controls"><div><span className="admin-sandbox-label">04 · Capture frame</span><div className="admin-sandbox-formats">{(["landscape","square","portrait"] as CaptureFormat[]).map(v=><button type="button" className={format===v?"active":""} key={v} onClick={()=>setFormat(v)}>{v==="landscape"?"16:9":v==="square"?"1:1":"9:16"}</button>)}</div></div><div className="admin-sandbox-actions"><button type="button" className="btn-secondary" onClick={randomize}>Randomize</button><button type="button" className="btn-primary" disabled={!ready} onClick={generate}>{active?"Generate new race →":"Generate RACE →"}</button></div></div>
      {!ready?<small className="admin-sandbox-hint">Add a seed and valid colors before the isolated RACE engine starts.</small>:null}
    </div>
    {active?<div className="admin-sandbox-stage-shell"><div className="admin-sandbox-stage-toolbar"><div><strong>RACE V2</strong><span>{active.playerCount} Orbs</span><span>3 laps</span><span>procedural Prismway</span><span>jump + weapons live</span></div><button type="button" className="btn-secondary" onClick={()=>void fullscreen()}>Fullscreen capture ↗</button></div><div ref={captureRef} className={`admin-sandbox-capture race-capture ${format}`}><RaceSandbox key={`${active.generation}:${format}`} playerCount={active.playerCount} style={{marble:active.marble,marbleSecondary:active.marbleSecondary,walls:active.walls,floor:active.floor,accent:active.accent}} seed={active.seed} generation={active.generation}/></div></div>:<div className="admin-sandbox-empty card race-empty"><div className="admin-sandbox-empty-orb"/><strong>The Prismway is sealed.</strong><span>Choose a population, palette and seed, then generate the first private RACE course. Nothing here can create, fund, settle or alter a production Orb.</span></div>}
  </section>;
}
