"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react"; import {useConnection,useWallet} from "@solana/wallet-adapter-react"; import {useWalletModal} from "@solana/wallet-adapter-react-ui"; import {LAMPORTS_PER_SOL} from "@solana/web3.js"; import Link from "next/link";
const safe=(v:unknown)=>{const s=String(v||"").trim(); return /^data:image\//i.test(s)||/^https?:\/\//i.test(s)||s.startsWith("/")?s:undefined};
const fmt=(l:number)=>{const s=l/LAMPORTS_PER_SOL;return s>=1?s.toFixed(2):s>=.01?s.toFixed(3):s.toFixed(4)};
export default function ConnectWallet({compact=false}:{compact?:boolean}){const w=useWallet(),{connection}=useConnection(),{setVisible}=useWalletModal(); const [open,setOpen]=useState(false),[bal,setBal]=useState<number|null>(null),[copied,setCopied]=useState(false); const ref=useRef<HTMLDivElement|null>(null); const pk=w.publicKey;
 useEffect(()=>{if(!w.connected||!pk){setBal(null);return}let off=false;connection.getBalance(pk,"confirmed").then(v=>!off&&setBal(v)).catch(()=>!off&&setBal(null));return()=>{off=true}},[w.connected,pk,connection]);
 useEffect(()=>{if(!open)return;const f=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",f);return()=>document.removeEventListener("mousedown",f)},[open]);
 const icon=useMemo(()=>safe((w.wallet?.adapter as {icon?:string}|undefined)?.icon),[w.wallet]); const connect=useCallback(()=>{if(w.wallet&&!w.connecting&&!w.connected){w.connect().catch(()=>setVisible(true));return}setVisible(true)},[w,setVisible]);
 if(!w.connected||!pk)return <button className={`btn-primary ${compact?"btn-small":""}`} onClick={connect} disabled={w.connecting}>{w.connecting?"Connecting…":"Connect wallet"}</button>;
 const addr=pk.toBase58(),short=`${addr.slice(0,4)}…${addr.slice(-4)}`;
 return <div className="wallet-wrap" ref={ref}><button className="wallet-chip" onClick={()=>setOpen(v=>!v)}>{icon?<img src={icon} alt=""/>:<i/>}<span>{short}</span>{bal!==null&&!compact?<small>{fmt(bal)} SOL</small>:null}<b>⌄</b></button>{open?<div className="wallet-menu"><div className="wallet-head"><span>Connected</span><strong>{short}</strong>{bal!==null?<small>{fmt(bal)} SOL</small>:null}</div><button onClick={async()=>{try{await navigator.clipboard.writeText(addr);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}}}>{copied?"Copied":"Copy address"}</button><Link href="/me" onClick={()=>setOpen(false)}>My Orbs</Link><button onClick={()=>{setOpen(false);setVisible(true)}}>Change wallet</button><button className="danger" onClick={()=>{void w.disconnect();setOpen(false)}}>Disconnect</button></div>:null}</div>;
}
