"use client"; import {useState} from "react"; import {useWallet} from "@solana/wallet-adapter-react"; import ConnectWallet from "@/components/ConnectWallet";
const names=["Identity","Prize","Game","Launch","Review","Share"];
export default function CreateWizard(){const[step,setStep]=useState(0),[difficulty,setDifficulty]=useState("Classic");const{connected}=useWallet();return <div className="wizard-layout"><aside className="wizard-nav">{names.map((n,i)=><button key={n} className={step===i?"active":""} onClick={()=>setStep(i)}>{i+1}. {n}</button>)}</aside><section className="wizard">
{step===0?<><span className="eyebrow">Step 1 of 6</span><h2>Who is hosting?</h2><p>Connect the identities that will own and promote this Orb. Wallet connection is live now; X connection arrives with the qualification backend.</p><div className="fields"><div className="field full"><label>Solana wallet</label>{connected?<div className="q-row ready"><span className="q-num">✓</span><div><strong>Wallet connected</strong><small>Ready for the future funding flow</small></div></div>:<ConnectWallet/>}</div><div className="field full"><label>X account</label><button className="btn-secondary" disabled>Connect X · next phase</button></div></div></>:null}
{step===1?<><span className="eyebrow">Step 2 of 6</span><h2>Choose the prize.</h2><p>The final build will reuse the proven SPL token picker. The displayed prize stays intact; the $1.10 Orbs fee is separate.</p><div className="fields"><div className="field"><label>Token</label><input placeholder="Search supported SPL token" disabled/></div><div className="field"><label>Prize amount</label><input placeholder="$6 minimum" disabled/></div><div className="field full"><label>Fee preview</label><input value="$1.10 equivalent in selected token · integration next phase" readOnly/></div></div></>:null}
{step===2?<><span className="eyebrow">Step 3 of 6</span><h2>Design the game.</h2><p>Pick target solve time and community colors. These settings become part of the shared game manifest.</p><div className="difficulty">{[["Quick","~5 min"],["Classic","~10 min"],["Brutal","~15 min"]].map(([n,t])=><button key={n} className={difficulty===n?"active":""} onClick={()=>setDifficulty(n)}><strong>{n}</strong><small>{t} target solve</small></button>)}</div><div className="fields"><div className="field"><label>Glass marble</label><input type="color" defaultValue="#5B5CF6"/></div><div className="field"><label>Maze walls</label><input type="color" defaultValue="#20E3D2"/></div></div></>:null}
{step===3?<><span className="eyebrow">Step 4 of 6</span><h2>Schedule launch.</h2><p>Give the post time to cook. The final funding transaction will commit the absolute start timestamp on-chain.</p><div className="fields"><div className="field"><label>Date</label><input type="date"/></div><div className="field"><label>Time</label><input type="time"/></div><div className="field full"><label>Share URL preview</label><input value="orbs.meme/orb/your-orb" readOnly/></div></div></>:null}
{step===4?<><span className="eyebrow">Step 5 of 6</span><h2>Review + fund.</h2><p>This is where Anchor will create the isolated prize vault, transfer the full prize, and send the separate protocol fee to the hardcoded treasury.</p><div className="q-list"><div className="q-row"><span className="q-num">1</span><div><strong>Prize escrow</strong><small>Anchor integration next phase</small></div></div><div className="q-row"><span className="q-num">2</span><div><strong>Game commitment</strong><small>Game system next phase</small></div></div><div className="q-row"><span className="q-num">3</span><div><strong>Fund Orb</strong><small>Disabled until program integration</small></div></div></div></>:null}
{step===5?<><span className="eyebrow">Step 6 of 6</span><h2>Share the Orb.</h2><p>After funding succeeds, this screen will reveal the permanent unique link and X share intent.</p><div className="fields"><div className="field full"><label>Public URL</label><input value="orbs.meme/orb/9xL4Q" readOnly/></div><button className="btn-primary" disabled>Copy link</button><button className="btn-secondary" disabled>Post to X</button></div></>:null}
<div className="wizard-actions"><button className="btn-ghost" disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))}>← Back</button><button className="btn-primary" disabled={step===names.length-1} onClick={()=>setStep(v=>Math.min(names.length-1,v+1))}>Continue →</button></div></section></div>}
